import type { LocalizedString } from './types';
const l = (en: string, es: string): LocalizedString => ({ en, es });
export interface BlogArticle { id: string; slug: LocalizedString; category: { slug: LocalizedString; title: LocalizedString }; title: LocalizedString; excerpt: LocalizedString; body: LocalizedString; publishedAt: string; relatedServices: string[]; relatedSolutions: string[]; }
const article = (id: string, slug: string, esSlug: string, category: string, esCategory: string, title: string, esTitle: string, excerpt: string, esExcerpt: string, body: string, esBody: string, services: string[], solutions: string[]): BlogArticle => ({ id, slug: l(slug, esSlug), category: { slug: l(category, esCategory), title: l(category.replace(/-/g, ' '), esCategory.replace(/-/g, ' ')) }, title: l(title, esTitle), excerpt: l(excerpt, esExcerpt), body: l(body, esBody), publishedAt: '2026-07-01', relatedServices: services, relatedSolutions: solutions });
export const blog: BlogArticle[] = [
  article('manufacturing-readiness', 'manufacturing-readiness-before-rfq', 'preparacion-de-manufactura-antes-del-rfq', 'manufacturing', 'manufactura', 'Manufacturing Readiness Before an RFQ', 'Preparación de manufactura antes de un RFQ', 'A strong RFQ starts with enough technical context to assess process, risk, and lead time.', 'Un RFQ sólido comienza con suficiente contexto técnico para evaluar proceso, riesgo y plazo.', 'An RFQ is not only a price request. It is the first test of whether the technical package can be executed consistently.\n\nInclude intended use, quantities, drawings, material requirements, and the acceptance criteria that matter most.', 'Un RFQ no es solo una solicitud de precio. Es la primera prueba de si el paquete técnico puede ejecutarse de forma consistente.\n\nIncluya uso previsto, cantidades, planos, requisitos de material y los criterios de aceptación más importantes.', ['engineering', 'strategic-sourcing'], ['custom-manufacturing']),
  article('china-manufacturing-controls', 'building-controls-for-china-manufacturing', 'controles-para-manufactura-en-china', 'china-manufacturing', 'manufactura-china', 'Building Controls for China Manufacturing', 'Cómo establecer controles para manufactura en China', 'Distance is manageable when responsibility, documentation, and release points are explicit.', 'La distancia es manejable cuando responsabilidad, documentación y puntos de liberación son explícitos.', 'Successful China manufacturing depends on more than supplier selection. Define the technical baseline, inspection plan, escalation path, and shipping release process before production begins.\n\nA qualified manufacturing ecosystem performs best when each party understands its decision rights.', 'La manufactura exitosa en China depende de más que seleccionar un proveedor. Defina la línea base técnica, el plan de inspección, la ruta de escalamiento y el proceso de liberación de envío antes de iniciar producción.\n\nUn ecosistema de manufactura calificado funciona mejor cuando cada parte comprende sus derechos de decisión.', ['supplier-qualification', 'quality-control'], ['metal-manufacturing']),
  article('dfm-early', 'why-dfm-belongs-at-project-start', 'por-que-el-dfm-debe-iniciar-el-proyecto', 'engineering', 'ingenieria', 'Why DFM Belongs at Project Start', 'Por qué el DFM debe iniciar el proyecto', 'Early manufacturability review exposes cost, quality, and schedule decisions while they are still manageable.', 'La revisión temprana de fabricabilidad revela decisiones de costo, calidad y plazo cuando aún son manejables.', 'Design for manufacturability is a structured conversation between product intent and process reality.\n\nIt should address tolerances, materials, interfaces, inspection methods, and likely failure modes before tooling or production commitments.', 'El diseño para manufacturabilidad es una conversación estructurada entre la intención del producto y la realidad del proceso.\n\nDebe abordar tolerancias, materiales, interfaces, métodos de inspección y modos de falla probables antes de comprometer herramentales o producción.', ['engineering', 'tooling'], ['plastic-injection', 'custom-manufacturing']),
  article('procurement-beyond-price', 'procurement-beyond-unit-price', 'compras-mas-alla-del-precio-unitario', 'procurement', 'compras', 'Procurement Beyond Unit Price', 'Compras más allá del precio unitario', 'A technically comparable offer reveals total execution risk, not only a unit price.', 'Una oferta técnicamente comparable revela el riesgo total de ejecución, no solo un precio unitario.', 'Price comparisons are meaningful only after scope, assumptions, and quality requirements are comparable.\n\nReview lead times, process route, tooling ownership, inspection, packaging, and change management alongside commercial terms.', 'Las comparaciones de precio son significativas solo cuando alcance, supuestos y requisitos de calidad son comparables.\n\nRevise plazos, ruta de proceso, propiedad de herramentales, inspección, embalaje y gestión de cambios junto con términos comerciales.', ['strategic-sourcing', 'supplier-qualification'], ['custom-manufacturing']),
  article('nearshoring-decision', 'nearshoring-and-global-manufacturing', 'nearshoring-y-manufactura-global', 'nearshoring', 'nearshoring', 'Nearshoring and Global Manufacturing', 'Nearshoring y manufactura global', 'Regional proximity is one input in a broader decision about capability, resilience, and program control.', 'La proximidad regional es un insumo en una decisión más amplia sobre capacidad, resiliencia y control de programa.', 'Nearshoring can simplify communication and logistics, but it does not replace technical qualification.\n\nEvaluate the entire execution model: process capability, supply continuity, quality controls, and response to engineering changes.', 'El nearshoring puede simplificar comunicación y logística, pero no reemplaza la calificación técnica.\n\nEvalúe el modelo completo de ejecución: capacidad de proceso, continuidad de suministro, controles de calidad y respuesta a cambios de ingeniería.', ['supply-chain-development', 'factory-audits'], ['industrial-equipment']),
  article('supply-chain-resilience', 'engineering-supply-chain-resilience', 'ingenieria-de-resiliencia-en-cadena-de-suministro', 'supply-chain', 'cadena-de-suministro', 'Engineering Supply Chain Resilience', 'Ingeniería de resiliencia en la cadena de suministro', 'Resilience is designed through visibility, qualified alternatives, and controlled technical data.', 'La resiliencia se diseña mediante visibilidad, alternativas calificadas y datos técnicos controlados.', 'A resilient supply chain starts with understanding process dependencies and single points of failure.\n\nMaintain current specifications, identify alternatives before disruption, and define the qualification work needed for any change.', 'Una cadena de suministro resiliente comienza entendiendo dependencias de proceso y puntos únicos de falla.\n\nMantenga especificaciones actualizadas, identifique alternativas antes de la interrupción y defina el trabajo de calificación necesario para cualquier cambio.', ['supply-chain-development', 'manufacturing-transfer'], ['custom-manufacturing']),
  article(
    'chinese-manufacturers-mexico',
    'why-chinese-manufacturers-are-moving-to-mexico',
    'por-que-los-fabricantes-chinos-se-mueven-a-mexico',
    'nearshoring',
    'nearshoring',
    'Why Chinese Manufacturers Are Moving to Mexico — And How We Help',
    'Por qué los fabricantes chinos se mueven a México — y cómo ayudamos',
    'The nearshoring wave is reshaping supply chains. Here is what we have learned helping manufacturing companies evaluate and execute their move from China to Mexico.',
    'La ola de nearshoring está reconfigurando las cadenas de suministro. Esto es lo que hemos aprendido ayudando a empresas a evaluar y ejecutar su traslado de China a México.',
    'Trade policy, logistics risk, and customer proximity are pushing more Chinese manufacturers to evaluate Mexico as a production base. The decision is rarely only about labor cost — it is about process capability, supplier ecosystems, and how quickly a plant can reach stable quality.\n\nCompanies that succeed treat nearshoring as a controlled manufacturing transfer: they freeze the technical baseline, qualify local and hybrid supply routes, and define inspection and ramp-up criteria before volumes move.\n\nTop Industrial supports that path with engineering review, supplier qualification, and production transfer oversight — connecting China manufacturing knowledge with execution requirements across Mexico and Latin America.',
    'La política comercial, el riesgo logístico y la proximidad al cliente están impulsando a más fabricantes chinos a evaluar México como base de producción. La decisión rara vez se trata solo del costo laboral: se trata de capacidad de proceso, ecosistemas de proveedores y la velocidad con la que una planta puede alcanzar calidad estable.\n\nLas empresas que tienen éxito tratan el nearshoring como una transferencia de manufactura controlada: congelan la línea base técnica, califican rutas de suministro locales e híbridas, y definen criterios de inspección y ramp-up antes de mover volúmenes.\n\nTop Industrial apoya ese camino con revisión de ingeniería, calificación de proveedores y supervisión de transferencia de producción — conectando el conocimiento de manufactura en China con los requisitos de ejecución en México y América Latina.',
    ['nearshoring-support', 'manufacturing-transfer'],
    ['custom-manufacturing'],
  ),
];