import type { LocalizedString } from './types';
const l = (en: string, es: string): LocalizedString => ({ en, es });
export interface CaseStudy {
  id: string;
  slug: LocalizedString;
  title: LocalizedString;
  industry: string;
  industryLabel: LocalizedString;
  scopeType: LocalizedString;
  outcome: LocalizedString;
  challenge: LocalizedString;
  scope: LocalizedString;
  approach: LocalizedString;
  execution: LocalizedString;
  result: LocalizedString;
  relatedSolutions: string[];
  relatedServices: string[];
}
export const caseStudies: CaseStudy[] = [
  {
    id: 'industrial-enclosure-program',
    slug: l('industrial-enclosure-program', 'programa-de-gabinetes-industriales'),
    title: l('Industrial Enclosure Program', 'Programa de Gabinetes Industriales'),
    industry: 'electronics',
    industryLabel: l('Industrial Equipment', 'Equipos Industriales'),
    scopeType: l('Sheet Metal · NEMA-Rated', 'Lámina Metálica · Clasificación NEMA'),
    outcome: l('Zero Critical Non-Conformances · 3 Production Batches', 'Cero No Conformidades Críticas · 3 Lotes de Producción'),
    challenge: l(
      'A growing equipment manufacturer needed a repeatable enclosure program across six NEMA-rated configurations — same internal mounting pattern, same gasket groove, same door latching engagement — but spanning different enclosure volumes. The challenge was not fabricating one enclosure; it was establishing a controlled production route that delivered consistent critical dimensions and gasket sealing across all six configurations, with the documentation discipline required by an equipment OEM shipping into industrial and outdoor environments. The buyer had previously experienced batch-to-batch dimensional drift that caused gasket sealing failures and door alignment complaints from the field.',
      'Un fabricante de equipos en crecimiento necesitaba un programa repetible de gabinetes en seis configuraciones clasificadas NEMA — mismo patrón de montaje interno, misma ranura de empaque, mismo enganche de cierre de puerta — pero abarcando diferentes volúmenes de gabinete. El reto no era fabricar un gabinete; era establecer una ruta de producción controlada que entregara dimensiones críticas consistentes y sellado de empaque a través de las seis configuraciones, con la disciplina documental requerida por un OEM de equipos que envía a entornos industriales y exteriores. El comprador había experimentado previamente deriva dimensional lote a lote que causó fallas de sellado de empaque y quejas de alineación de puerta desde el campo.',
    ),
    scope: l(
      'Sheet metal fabrication, surface finishing (powder coat), hardware installation, mechanical assembly, and dimensional inspection for a family of NEMA 12 and NEMA 4 rated enclosures in 6 size configurations. Annual volume: 4,800 units across the family. Each enclosure carried 14 critical-to-quality (CTQ) dimensions including gasket groove width, door-to-body gap, latching engagement depth, and mounting pattern location. Documentation pack per shipment: dimensional report, material certificate (3.1 per EN 10204), powder coat thickness record, and configuration control record.',
      'Fabricación de lámina metálica, acabado superficial (pintura en polvo), instalación de herrajes, ensamblaje mecánico e inspección dimensional para una familia de gabinetes clasificados NEMA 12 y NEMA 4 en 6 configuraciones de tamaño. Volumen anual: 4.800 unidades en la familia. Cada gabinete cargaba 14 dimensiones críticas para la calidad (CTQ) incluyendo ancho de ranura de empaque, brecha puerta-a-cuerpo, profundidad de enganche de cierre y ubicación de patrón de montaje. Paquete documental por envío: informe dimensional, certificado de material (3.1 según EN 10204), registro de espesor de pintura en polvo y registro de control de configuración.',
    ),
    approach: l(
      'We standardized interface dimensions and mounting patterns across all six configurations — the same gasket groove geometry, the same door hinge location, the same latching cam engagement. We then established a first-article inspection plan around the 14 CTQ dimensions, with full dimensional overlay against the drawing for the first article of each configuration. A PFMEA was facilitated with the supplier to anticipate process failure modes — weld distortion, bend variation, powder coat thickness drift — and the control plan was updated to address each. Sampling was set at AQL 1.0 for general dimensions and 100% for the four critical-to-function dimensions (gasket groove, door gap, latching, mounting).',
      'Estandarizamos dimensiones de interfaz y patrones de montaje a través de las seis configuraciones — la misma geometría de ranura de empaque, la misma ubicación de bisagra de puerta, el mismo enganche de leva de cierre. Luego establecimos un plan de inspección de primer artículo alrededor de las 14 dimensiones CTQ, con superposición dimensional completa contra el plano para el primer artículo de cada configuración. Se facilitó un PFMEA con el proveedor para anticipar modos de falla de proceso — distorsión de soldadura, variación de doblado, deriva de espesor de pintura en polvo — y se actualizó el plan de control para abordar cada uno. El muestreo se fijó en AQL 1,0 para dimensiones generales y 100% para las cuatro dimensiones críticas para función (ranura de empaque, brecha de puerta, cierre, montaje).',
    ),
    execution: l(
      'We qualified two fabrication suppliers for different size ranges — each supplier was qualified through a structured assessment covering equipment capability (CNC turret punch, press brake tonnage and length, weld equipment), quality system maturity (ISO 9001 baseline, control plan review, calibration system), and program execution (change control, communication discipline). First builds of each configuration were coordinated with full dimensional reports against the 14 CTQs; configurations were released to production only when all CTQs verified within tolerance. Configuration control was documented for repeat ordering — part number, configuration code, revision level, and BOM pointer. PPAP-equivalent documentation was maintained at Level 3 for the enclosure family.',
      'Calificamos dos proveedores de fabricación para distintos rangos de tamaño — cada proveedor se calificó a través de una evaluación estructurada que cubrió capacidad de equipo (punzón de torreta CNC, tonelaje y longitud de prensa dobladora, equipo de soldadura), madurez del sistema de calidad (línea base ISO 9001, revisión de plan de control, sistema de calibración) y ejecución de programa (control de cambios, disciplina de comunicación). Las primeras construcciones de cada configuración se coordinaron con informes dimensionales completos contra los 14 CTQs; las configuraciones se liberaron a producción solo cuando todos los CTQs verificaron dentro de tolerancia. El control de configuración se documentó para pedidos repetidos — número de parte, código de configuración, nivel de revisión y puntero BOM. Se mantuvo documentación equivalente a PPAP nivel 3 para la familia de gabinetes.',
    ),
    result: l(
      'Controlled production route supporting repeat orders with consistent lead times (96% on-time delivery across the first 12 months). Engineering change process established for future configuration updates — changes flow through documented change control before reaching the production line. Zero critical non-conformances across the first 3 production batches. Process capability (Cpk) verified at ≥ 1.33 on the four critical-to-function dimensions. The buyer retired the prior supplier and consolidated the enclosure family with the two qualified sources — reducing total cost of ownership and eliminating the field complaints that had triggered the program.',
      'Ruta de producción controlada que respalda pedidos repetidos con plazos consistentes (96% de entrega a tiempo en los primeros 12 meses). Proceso de cambio de ingeniería establecido para futuras actualizaciones de configuración — los cambios fluyen por control de cambios documentado antes de llegar a la línea de producción. Cero no conformidades críticas en los primeros 3 lotes de producción. Capacidad de proceso (Cpk) verificada en ≥ 1,33 en las cuatro dimensiones críticas para función. El comprador retiró al proveedor anterior y consolidó la familia de gabinetes con las dos fuentes calificadas — reduciendo el costo total de propiedad y eliminando las quejas de campo que habían disparado el programa.',
    ),
    relatedSolutions: ['metal-manufacturing', 'custom-manufacturing'],
    relatedServices: ['engineering', 'quality-control', 'project-management'],
  },
  {
    id: 'water-skid-integration',
    slug: l('water-skid-integration', 'integracion-de-skid-de-agua'),
    title: l('Water Treatment Skid Integration', 'Integración de Skid de Tratamiento de Agua'),
    industry: 'water-treatment',
    industryLabel: l('Water Treatment', 'Tratamiento de Agua'),
    scopeType: l('Skid Integration · ASME', 'Integración de Skid · ASME'),
    outcome: l('Field-Ready Package · Single Commissioning Pass', 'Paquete Listo para Campo · Puesta en Marcha en Una Sola Pasada'),
    challenge: l(
      'A project required coordinated fabrication and integration of a compact water treatment process skid — structural frame, vessel mounting, piping, instrumentation, and electrical panel — with the integration complexity that frequently causes field rework. The end customer required a field-ready package: arriving with verified interface alignment, complete documentation (P&ID, GA, electrical schematics, material certificates, hydrotest records, calibration records, operating manuals), and a single-pass commissioning path. The integration spanned three supplier specializations — structural/piping, instrumentation, electrical/control — and the failure mode of unmanaged integration is interface incompatibility discovered at commissioning, when rework is expensive and schedule slips cascade.',
      'Un proyecto requirió fabricación e integración coordinada de un skid compacto de proceso de tratamiento de agua — bastidor estructural, montaje de vasos, tubería, instrumentación y panel eléctrico — con la complejidad de integración que frecuentemente causa retrabajo en campo. El cliente final requería un paquete listo para campo: llegando con alineación de interfaces verificada, documentación completa (P&ID, GA, esquemas eléctricos, certificados de material, registros de hidroprueba, registros de calibración, manuales de operación) y un camino de puesta en marcha en una sola pasada. La integración abarcó tres especializaciones de proveedor — estructural/tubería, instrumentación, eléctrico/control — y el modo de falla de integración no gestionada es incompatibilidad de interfaz descubierta en la puesta en marcha, cuando el retrabajo es costoso y los deslizamientos de cronograma se propagan.',
    ),
    scope: l(
      'Coordinated fabrication and integration of a compact water treatment process skid — structural frame (316L stainless), vessel mounting (2 process vessels with ASME Section VIII stamping), piping (316L stainless, ASME B31.3 fabrication, hydrostatically tested), instrumentation (8 process instruments — flow, pressure, level, pH, conductivity), and electrical control panel (UL 508A). Skid footprint: 2.4m × 1.5m × 2.2m. Integration scope: mechanical completion, electrical completion, functional test, FAT before shipment. Documentation pack: P&ID, GA, electrical schematics, instrument list, I/O list, material certificates (3.1 per EN 10204), hydrotest records, calibration records, operating manual.',
      'Fabricación e integración coordinada de un skid compacto de proceso de tratamiento de agua — bastidor estructural (acero inoxidable 316L), montaje de vasos (2 vasos de proceso con estampado ASME Sección VIII), tubería (acero inoxidable 316L, fabricación ASME B31.3, probada hidrostáticamente), instrumentación (8 instrumentos de proceso — flujo, presión, nivel, pH, conductividad) y panel eléctrico de control (UL 508A). Huella del skid: 2,4m × 1,5m × 2,2m. Alcance de integración: completitud mecánica, completitud eléctrica, prueba funcional, FAT antes del envío. Paquete documental: P&ID, GA, esquemas eléctricos, lista de instrumentos, lista de I/O, certificados de material (3.1 según EN 10204), registros de hidroprueba, registros de calibración, manual de operación.',
    ),
    approach: l(
      'We reviewed the P&ID and general arrangement drawings against the fabrication capability and the operational envelope — flow rates, pressures, temperatures, fluid composition. Interface risks between structural, piping, instrumentation, and electrical subsystems were identified before build: vessel-to-frame mounting loads, pipe-to-vessel nozzle loads, instrument-to-pipe mounting positions, cable routing paths between instruments and control panel. Each interface was documented with a defined tolerance and acceptance criterion. The build sequence was planned to surface interface issues at the earliest possible point — structural completion before vessel mounting, vessel mounting before piping, piping before instrumentation, instrumentation before electrical.',
      'Revisamos los planos P&ID y de arreglo general contra la capacidad de fabricación y la envolvente operativa — caudales, presiones, temperaturas, composición del fluido. Los riesgos de interfaz entre los subsistemas estructural, tubería, instrumentación y eléctrico se identificaron antes de la construcción: cargas de montaje de vaso-a-bastidor, cargas de tubería-a-boquilla de vaso, posiciones de montaje de instrumento-a-tubería, rutas de cableado entre instrumentos y tablero de control. Cada interfaz se documentó con una tolerancia definida y un criterio de aceptación. La secuencia de construcción se planificó para exponer problemas de interfaz en el punto más temprano posible — completitud estructural antes del montaje de vasos, montaje de vasos antes de tubería, tubería antes de instrumentación, instrumentación antes de eléctrico.',
    ),
    execution: l(
      'We managed fabrication across metal and piping suppliers — the structural frame was fabricated by a qualified stainless steel fabricator (316L, AWS D1.6 weld procedures, pickled and passivated surface). The vessels were sourced from a code-stamped fabricator (ASME Section VIII, U-stamp) with material certificates and hydrotest records. Piping was fabricated to ASME B31.3 by the same fabricator, hydrostatically tested at 1.5× design pressure, with material traceability per lot. Instrumentation was sourced from authorized distributors and calibrated before installation. The control panel was built to UL 508A by a qualified panel shop. Integration was staged — mechanical completion (frame, vessels, piping, instruments installed), electrical completion (panel wired, instruments terminated), functional test (each instrument verified, each control loop tested), FAT (full functional demonstration with the customer witness).',
      'Gestionamos la fabricación entre proveedores de metal y tubería — el bastidor estructural lo fabricó un fabricante calificado de acero inoxidable (316L, procedimientos de soldadura AWS D1.6, superficie pickled y pasivada). Los vasos se obtuvieron de un fabricante con estampado de código (ASME Sección VIII, U-stamp) con certificados de material y registros de hidroprueba. La tubería se fabricó según ASME B31.3 por el mismo fabricante, probada hidrostáticamente a 1,5× la presión de diseño, con trazabilidad de material por lote. La instrumentación se obtuvo de distribuidores autorizados y se calibró antes de la instalación. El tablero de control se construyó según UL 508A por un taller de tableros calificado. La integración se escalonó — completitud mecánica (bastidor, vasos, tubería, instrumentos instalados), completitud eléctrica (tablero cableado, instrumentos terminados), prueba funcional (cada instrumento verificado, cada lazo de control probado), FAT (demostración funcional completa con testigo del cliente).',
    ),
    result: l(
      'Integrated skid shipped with complete documentation package — P&ID, GA, electrical schematics, instrument list, I/O list, material certificates (3.1 per EN 10204), hydrotest records, calibration records, operating manual. Ready for field installation with verified interface alignment. The skid passed site acceptance test (SAT) on the first attempt — single-pass commissioning with no field rework. Vessel and piping hydrotest records supported the customer\'s commissioning paperwork; material certificates supported the customer\'s regulatory filing. The integration approach was adopted by the customer as a standard for subsequent skid projects.',
      'Skid integrado enviado con paquete completo de documentación — P&ID, GA, esquemas eléctricos, lista de instrumentos, lista de I/O, certificados de material (3.1 según EN 10204), registros de hidroprueba, registros de calibración, manual de operación. Listo para instalación en campo con alineación de interfaces verificada. El skid pasó la prueba de aceptación en sitio (SAT) en el primer intento — puesta en marcha en una sola pasada sin retrabajo de campo. Los registros de hidroprueba de vasos y tubería respaldaron el papeleo de puesta en marcha del cliente; los certificados de material respaldaron la presentación regulatoria del cliente. El enfoque de integración fue adoptado por el cliente como estándar para proyectos subsecuentes de skid.',
    ),
    relatedSolutions: ['water-treatment', 'industrial-equipment'],
    relatedServices: ['engineering', 'manufacturing-supervision', 'quality-control'],
  },
  {
    id: 'molded-component-transfer',
    slug: l('molded-component-transfer', 'transferencia-de-componente-moldeado'),
    title: l('Molded Component Transfer', 'Transferencia de Componente Moldeado'),
    industry: 'automotive',
    industryLabel: l('Automotive', 'Automotriz'),
    scopeType: l('Mold Transfer · PPAP', 'Transferencia de Molde · PPAP'),
    outcome: l('Dimensional Continuity · 50-Sample Verification', 'Continuidad Dimensional · Verificación de 50 Muestras'),
    challenge: l(
      'A legacy molded component — interior trim piece for a vehicle program still in series production — required production transfer with controlled dimensional continuity. The originating supplier had been producing the part for 7 years; the buyer was consolidating suppliers and the originating source was being retired. The challenge was that the part had been in production long enough that informal process knowledge had accumulated — operators adjusting parameters by feel, undocumented mold maintenance, the mold itself having been reworked multiple times. A naive transfer would have produced parts that met the drawing but differed dimensionally from the parts the customer had been receiving, causing fit-and-finish complaints in the vehicle.',
      'Un componente moldeado heredado — pieza de acabado interior para un programa de vehículo aún en producción en serie — requería transferencia de producción con continuidad dimensional controlada. El proveedor de origen había estado produciendo la pieza por 7 años; el comprador estaba consolidando proveedores y la fuente de origen se estaba retirando. El reto era que la pieza había estado en producción el tiempo suficiente para que se acumulara conocimiento de proceso informal — operadores ajustando parámetros por sensación, mantenimiento de molde no documentado, el molde mismo re trabajado múltiples veces. Una transferencia ingenua habría producido piezas que cumplían el plano pero diferían dimensionalmente de las piezas que el cliente había estado recibiendo, causando quejas de ajuste y acabado en el vehículo.',
    ),
    scope: l(
      'Production transfer of a legacy injection-molded interior trim component from an existing supplier to a new qualified facility, with controlled dimensional continuity. Component: glass-filled PA6 interior trim, single-cavity mold, annual volume 120,000 units. The mold had been in service 7 years and had been reworked twice (gate modification, ejector pin replacement). The customer required PPAP Level 3 submission and dimensional continuity within the existing process variation — no visible change to the part as received at the assembly plant.',
      'Transferencia de producción de un componente heredado de acabado interior moldeado por inyección desde un proveedor existente hacia una nueva planta calificada, con continuidad dimensional controlada. Componente: PA6 con carga de fibra de vidrio, acabado interior, molde de una cavidad, volumen anual 120.000 unidades. El molde había estado en servicio 7 años y había sido re trabajado dos veces (modificación de alimentación, reemplazo de pin de expulsión). El cliente requería presentación PPAP nivel 3 y continuidad dimensional dentro de la variación existente del proceso — ningún cambio visible a la pieza tal como se recibía en la planta de ensamblaje.',
    ),
    approach: l(
      'We analyzed the current part data and established a comparison baseline — dimensional measurement of 50 sample parts from the originating source across the full production range, capturing the actual process variation rather than the drawing tolerance. Critical dimensions and aesthetic requirements that defined transfer success were identified: 12 dimensional CTQs (including mounting boss locations, snap-fit engagement, surface flatness) and 4 aesthetic criteria (color match delta-E, surface finish, gloss level, weld-line position). The receiving facility was qualified against the baseline — same resin grade, same process parameters as documented, dimensional overlay of new-source parts against the originating source data.',
      'Analizamos los datos actuales de la pieza y establecimos una línea base de comparación — medición dimensional de 50 piezas de muestra de la fuente de origen a lo largo del rango completo de producción, capturando la variación real del proceso en lugar de la tolerancia del plano. Se identificaron las dimensiones críticas y requisitos estéticos que definieron el éxito de la transferencia: 12 CTQs dimensionales (incluyendo ubicaciones de boss de montaje, enganche de snap-fit, planicidad de superficie) y 4 criterios estéticos (delta-E de color, acabado superficial, nivel de brillo, posición de línea de soldadura). La planta receptora se calificó contra la línea base — misma calidad de resina, mismos parámetros de proceso según lo documentado, superposición dimensional de piezas de nueva fuente contra los datos de la fuente de origen.',
    ),
    execution: l(
      'We qualified the new mold environment and production capability — the existing mold was inspected, refurbished where needed (ejector pin replacement, gate touch-up), and qualified in the new press at the receiving facility. First-article samples (50 parts across the production range) were run with full dimensional overlay against the baseline data — 12 CTQs measured, color match delta-E verified against master, surface finish verified against golden sample. Process parameters were adjusted within the documented process window to match the originating source\'s dimensional output within tolerance. PPAP Level 3 documentation was assembled — design record, authorized engineering change documents, customer engineering approval, DFMEA, PFMEA, control plan, MSA, dimensional results, material/performance test results, initial process studies (Cpk), qualified laboratory documentation, AAR appearance approval, sample product, master sample, checking aids, and customer-specific requirements.',
      'Calificamos el nuevo ambiente de molde y la capacidad de producción — el molde existente se inspeccionó, se refurbeció donde se necesitó (reemplazo de pin de expulsión, retoque de alimentación) y se calificó en la nueva prensa en la planta receptora. Las muestras de primer artículo (50 piezas a lo largo del rango de producción) se corrieron con superposición dimensional completa contra los datos de la línea base — 12 CTQs medidos, delta-E de color verificado contra master, acabado superficial verificado contra muestra dorada. Los parámetros de proceso se ajustaron dentro de la ventana de proceso documentada para coincidir con la salida dimensional de la fuente de origen dentro de tolerancia. La documentación PPAP nivel 3 se ensambló — registro de diseño, documentos autorizados de cambio de ingeniería, aprobación de ingeniería del cliente, DFMEA, PFMEA, plan de control, MSA, resultados dimensionales, resultados de prueba de material/desempeño, estudios iniciales de proceso (Cpk), documentación de laboratorio calificado, aprobación de apariencia AAR, muestra de producto, muestra master, ayudas de verificación y requisitos específicos del cliente.',
    ),
    result: l(
      'Successful transfer with dimensional continuity confirmed across 50 sample parts — all 12 CTQs within tolerance, color match delta-E within target, surface finish within golden-sample tolerance. Production approved at new facility with documented process settings. Cpk ≥ 1.33 verified on critical dimensions after stabilization. Original tooling retired on schedule per the consolidation plan. The buyer avoided the field complaints that would have accompanied a less-controlled transfer — the assembly plant saw no change in part behavior. PPAP documentation supported the customer\'s internal change-control approval without escalation.',
      'Transferencia exitosa con continuidad dimensional confirmada en 50 piezas de muestra — los 12 CTQs dentro de tolerancia, delta-E de color dentro del objetivo, acabado superficial dentro de la tolerancia de muestra dorada. Producción aprobada en la nueva planta con ajustes de proceso documentados. Cpk ≥ 1,33 verificado en dimensiones críticas tras estabilización. Herramental original retirado según cronograma del plan de consolidación. El comprador evitó las quejas de campo que habrían acompañado a una transferencia menos controlada — la planta de ensamblaje no vio cambio en el comportamiento de la pieza. La documentación PPAP respaldó la aprobación de control de cambios interno del cliente sin escalamiento.',
    ),
    relatedSolutions: ['plastic-injection'],
    relatedServices: ['manufacturing-transfer', 'tooling', 'quality-control'],
  },
  {
    id: 'mining-spare-part-reconstruction',
    slug: l('mining-spare-part-reconstruction', 'reconstruccion-de-repuesto-minero'),
    title: l('Mining Spare Part Reconstruction', 'Reconstrucción de Repuesto Minero'),
    industry: 'mining',
    industryLabel: l('Mining', 'Minería'),
    scopeType: l('Reverse Engineering · Material Upgrade', 'Ingeniería Inversa · Mejora de Material'),
    outcome: l('Lead Time 16w → 6w · Service Life +60%', 'Plazo 16s → 6s · Vida Útil +60%'),
    challenge: l(
      'An operating mining site needed a replacement component — a wear liner for a slurry pump — with incomplete legacy documentation and no available spare parts. The OEM had exited the market; the original drawings were lost; the site was running on the last available spare. Each day of downtime at the affected process step cost the operation approximately $24,000 in lost production. The site needed a controlled spare-part source — not a one-off reverse engineering exercise — that could supply future replacements on a predictable schedule. Material upgrade was a secondary objective: the original part\'s wear life was the bottleneck in the maintenance cycle, and a longer-wearing material would reduce change-out frequency and labor exposure.',
      'Una operación minera necesitaba un componente de reemplazo — un revestimiento de desgaste para una bomba de pasta — con documentación heredada incompleta y sin repuestos disponibles. El OEM había salido del mercado; los planos originales se perdieron; el sitio operaba con el último repuesto disponible. Cada día de tiempo muerto en el paso de proceso afectado costaba a la operación aproximadamente $24.000 en producción perdida. El sitio necesitaba una fuente controlada de repuestos — no un ejercicio de ingeniería inversa de una sola vez — que pudiera suministrar reemplazos futuros en un cronograma predecible. La mejora de material era un objetivo secundario: la vida al desgaste de la pieza original era el cuello de botella en el ciclo de mantenimiento, y un material de mayor resistencia al desgaste reduciría la frecuencia de cambio y la exposición laboral.',
    ),
    scope: l(
      'Reverse-engineered replacement wear liner for a slurry pump at an operating mining site, with incomplete legacy documentation and no available spare parts. Original documentation: partial 2D drawing (missing tolerance information, missing material specification). Original samples: 3 worn liners from the site\'s inventory, wear patterns documented. Material specification: original was chromium cast iron (15% Cr), wear life approximately 1,800 hours. Target: full engineering package, qualified manufacturing source, material upgrade opportunity assessment, and repeatable re-order path. Lead time target: ≤ 8 weeks from order to delivery (vs. 16+ weeks for OEM equivalent before OEM exit).',
      'Revestimiento de desgaste de reemplazo reconstruido por ingeniería inversa para una bomba de pasta en un sitio minero en operación, con documentación heredada incompleta y sin repuestos disponibles. Documentación original: plano 2D parcial (faltaba información de tolerancia, faltaba especificación de material). Muestras originales: 3 revestimientos desgastados del inventario del sitio, patrones de desgaste documentados. Especificación de material: original era hierro colado al cromo (15% Cr), vida al desgaste aproximadamente 1.800 horas. Objetivo: paquete completo de ingeniería, fuente de manufactura calificada, evaluación de oportunidad de mejora de material y camino de re-orden repetible. Objetivo de plazo: ≤ 8 semanas desde el pedido hasta la entrega (vs. 16+ semanas para el equivalente OEM antes de la salida del OEM).',
    ),
    approach: l(
      'We received the worn physical samples and the partial drawings, then used 3D scanning to capture the current geometry of the least-worn sample (the worn surfaces were interpreted based on wear pattern analysis, not measured directly). Cross-referenced the scan data with the available 2D drawing to verify dimensions, then reconstructed a complete engineering package: 2D drawings with tolerance information derived from functional intent (not from the worn sample), 3D CAD model for manufacturing reference, material specification based on operating-environment analysis (slurry velocity, particle size, pH, temperature), and inspection plan. The material specification presented a documented upgrade opportunity — high-chromium white iron (25% Cr) with documented wear test data showing approximately 1.6× the wear life of the original 15% Cr material.',
      'Recibimos las muestras físicas desgastadas y los planos parciales, luego usamos escaneo 3D para capturar la geometría actual de la muestra menos desgastada (las superficies desgastadas se interpretaron basadas en análisis de patrón de desgaste, no se midieron directamente). Contrastamos los datos de escaneo con el plano 2D disponible para verificar dimensiones, luego reconstruimos un paquete completo de ingeniería: planos 2D con información de tolerancia derivada de la intención funcional (no de la muestra desgastada), modelo CAD 3D para referencia de manufactura, especificación de material basada en análisis de entorno operativo (velocidad de pasta, tamaño de partícula, pH, temperatura) y plan de inspección. La especificación de material presentó una oportunidad documentada de mejora — hierro blanco alto en cromo (25% Cr) con datos documentados de prueba de desgaste mostrando aproximadamente 1,6× la vida al desgaste del material original 15% Cr.',
    ),
    execution: l(
      'We produced a prototype from the reconstructed drawings using the upgraded material specification (25% Cr high-chromium white iron). The foundry was qualified for high-chromium iron casting with documented heat treatment capability (austenitizing, air quench, temper) and hardness verification (HRc 60-64 target). Prototype was validated against the worn reference samples — dimensional fit to pump housing verified with the site maintenance team, wear surface compared to the original samples under simulated slurry conditions. Site team confirmed fit and function. Material specification was confirmed for series production — heat treatment parameters, hardness range, microstructure acceptance criteria documented in the engineering package.',
      'Producimos un prototipo a partir de los planos reconstruidos usando la especificación mejorada de material (25% Cr hierro blanco alto en cromo). La fundición se calificó para colada de hierro alto en cromo con capacidad documentada de tratamiento térmico (austenitizado, enfriamiento al aire, revenido) y verificación de dureza (HRc 60-64 objetivo). El prototipo se validó contra las muestras de referencia desgastadas — ajuste dimensional a la carcasa de la bomba verificado con el equipo de mantenimiento del sitio, superficie de desgaste comparada con las muestras originales bajo condiciones simuladas de pasta. El equipo del sitio confirmó ajuste y función. La especificación de material se confirmó para producción en serie — parámetros de tratamiento térmico, rango de dureza, criterios de aceptación de microestructura documentados en el paquete de ingeniería.',
    ),
    result: l(
      'Component installed and operating in the slurry pump at the affected process step. Engineering package archived for future reordering — the site now has a controlled spare-part source with predictable lead time. Lead time reduced from 16+ weeks (OEM, before exit) to 6 weeks (reconstructed source). Material upgrade extended expected service life from approximately 1,800 hours to approximately 2,900 hours — a 60% improvement that reduces change-out frequency and labor exposure at the site. The same approach was subsequently applied to three additional wear components on the same process line, each with similar improvements.',
      'Componente instalado y operando en la bomba de pasta en el paso de proceso afectado. Paquete de ingeniería archivado para futuros reórdenes — el sitio ahora tiene una fuente controlada de repuestos con plazo predecible. Plazo reducido de 16+ semanas (OEM, antes de la salida) a 6 semanas (fuente reconstruida). La mejora de material extendió la vida útil esperada de aproximadamente 1.800 horas a aproximadamente 2.900 horas — una mejora del 60% que reduce la frecuencia de cambio y la exposición laboral en el sitio. El mismo enfoque se aplicó posteriormente a tres componentes adicionales de desgaste en la misma línea de proceso, cada uno con mejoras similares.',
    ),
    relatedSolutions: ['metal-manufacturing', 'custom-manufacturing'],
    relatedServices: ['reverse-engineering', 'engineering', 'quality-control'],
  },
];
