import type { LocalizedString } from './types';
const l = (en: string, es: string): LocalizedString => ({ en, es });
export interface ProcessStep { id: string; title: LocalizedString; objective: LocalizedString; inputs: LocalizedString; outputs: LocalizedString; buyerRole: LocalizedString; }
const step = (id: string, en: string, es: string, objective: string, objetivo: string, inputs: string, entradas: string, outputs: string, salidas: string, buyer: string, comprador: string): ProcessStep => ({ id, title: l(en, es), objective: l(objective, objetivo), inputs: l(inputs, entradas), outputs: l(outputs, salidas), buyerRole: l(buyer, comprador) });
export const process: ProcessStep[] = [
  step('requirements', 'Requirements', 'Requisitos', 'Establish the technical and commercial brief.', 'Establecer el informe técnico y comercial.', 'Application, quantities, drawings, target dates.', 'Aplicación, cantidades, planos, fechas objetivo.', 'Confirmed scope and open-item list.', 'Alcance confirmado y lista de pendientes.', 'Provide context and approve priorities.', 'Aportar contexto y aprobar prioridades.'),
  step('engineering-review', 'Engineering Review', 'Revisión de ingeniería', 'Confirm manufacturability and interfaces.', 'Confirmar fabricabilidad e interfaces.', 'Technical package and samples where available.', 'Paquete técnico y muestras cuando estén disponibles.', 'Review record and recommendations.', 'Registro de revisión y recomendaciones.', 'Clarify intended use and technical decisions.', 'Aclarar uso previsto y decisiones técnicas.'),
  step('supplier-qualification', 'Supplier Qualification', 'Calificación de proveedores', 'Match the requirement to qualified capability.', 'Relacionar el requisito con capacidad calificada.', 'Process and quality requirements.', 'Requisitos de proceso y calidad.', 'Qualified execution route.', 'Ruta de ejecución calificada.', 'Confirm acceptance criteria.', 'Confirmar criterios de aceptación.'),
  step('quotation', 'Quotation', 'Cotización', 'Provide a transparent scope, lead time, and commercial basis.', 'Proporcionar alcance, plazo y base comercial transparentes.', 'Approved scope and assumptions.', 'Alcance y supuestos aprobados.', 'Quotation with assumptions and schedule.', 'Cotización con supuestos y cronograma.', 'Review scope before award.', 'Revisar alcance antes de adjudicar.'),
  step('prototype', 'Prototype', 'Prototipo', 'Validate critical design and process assumptions.', 'Validar supuestos críticos de diseño y proceso.', 'Released prototype scope.', 'Alcance de prototipo liberado.', 'Samples and validation feedback.', 'Muestras y retroalimentación de validación.', 'Test samples in the intended application.', 'Probar muestras en la aplicación prevista.'),
  step('production', 'Production', 'Producción', 'Execute the approved production plan.', 'Ejecutar el plan de producción aprobado.', 'Released drawings, tooling, and plan.', 'Planos liberados, herramentales y plan.', 'Produced parts or assemblies.', 'Piezas o conjuntos producidos.', 'Manage approved changes promptly.', 'Gestionar cambios aprobados con prontitud.'),
  step('inspection', 'Inspection', 'Inspección', 'Verify conformance before release.', 'Verificar conformidad antes de liberar.', 'Inspection plan and acceptance criteria.', 'Plan de inspección y criterios de aceptación.', 'Inspection record and release status.', 'Registro de inspección y estado de liberación.', 'Review exceptions requiring disposition.', 'Revisar excepciones que requieren disposición.'),
  step('shipping', 'Shipping', 'Envío', 'Deliver protected product with required documents.', 'Entregar producto protegido con documentos requeridos.', 'Released product and shipping instructions.', 'Producto liberado e instrucciones de envío.', 'Shipment and document pack.', 'Envío y paquete documental.', 'Confirm receiving and import requirements.', 'Confirmar requisitos de recepción e importación.'),
  step('after-sales', 'After-Sales Support', 'Soporte posventa', 'Maintain continuity for installed products and future requirements.', 'Mantener continuidad para productos instalados y requisitos futuros.', 'Field feedback and service requirements.', 'Retroalimentación de campo y requisitos de servicio.', 'Support actions and improvement record.', 'Acciones de soporte y registro de mejora.', 'Share operating feedback and forecasts.', 'Compartir retroalimentación operativa y pronósticos.'),
];
