import type { LocalizedString } from './types';
const l = (en: string, es: string): LocalizedString => ({ en, es });
export interface ProcessStep { id: string; title: LocalizedString; objective: LocalizedString; inputs: LocalizedString; outputs: LocalizedString; buyerRole: LocalizedString; }
const step = (id: string, en: string, es: string, objective: string, objetivo: string, inputs: string, entradas: string, outputs: string, salidas: string, buyer: string, comprador: string): ProcessStep => ({ id, title: l(en, es), objective: l(objective, objetivo), inputs: l(inputs, entradas), outputs: l(outputs, salidas), buyerRole: l(buyer, comprador) });
export const process: ProcessStep[] = [
  step(
    'requirements',
    'Requirements & Scope Definition',
    'Definición de Requisitos y Alcance',
    'Establish the technical and commercial brief — application, quantities, drawings, target dates, regulatory regime, and the acceptance criteria that will govern the program.',
    'Establecer el informe técnico y comercial — aplicación, cantidades, planos, fechas objetivo, régimen regulatorio y los criterios de aceptación que gobernarán el programa.',
    'Application context, target annual volume and order profile, available drawings / 3D models / BOM, material specifications, target dates, regulatory and documentation requirements, target cost where defined.',
    'Contexto de aplicación, volumen anual objetivo y perfil de pedido, planos / modelos 3D / BOM disponibles, especificaciones de material, fechas objetivo, requisitos regulatorios y documentales, costo objetivo cuando esté definido.',
    'Confirmed scope statement, open-item register with owners and due dates, technical and commercial baseline for engineering review and quotation.',
    'Declaración de alcance confirmada, registro de ítems abiertos con responsables y fechas, línea base técnica y comercial para revisión de ingeniería y cotización.',
    'Provide application context and confirm priorities. Approve scope statement before engineering review begins. Designate the technical and commercial decision-makers for the program.',
    'Aportar contexto de aplicación y confirmar prioridades. Aprobar la declaración de alcance antes de que comience la revisión de ingeniería. Designar los responsables técnicos y comerciales del programa.',
  ),
  step(
    'engineering-review',
    'Engineering Review & DFM',
    'Revisión de Ingeniería y DFM',
    'Confirm manufacturability and interfaces — apply DFM/DFA, tolerance studies, DFMEA, and CTQ identification before tooling or supplier commitment.',
    'Confirmar fabricabilidad e interfaces — aplicar DFM/DFA, estudios de tolerancia, DFMEA e identificación de CTQ antes del compromiso de herramentales o proveedores.',
    'Technical package (drawings, BOM, specifications, intended use), samples where available, prior quality history, regulatory regime, volume profile.',
    'Paquete técnico (planos, BOM, especificaciones, uso previsto), muestras cuando estén disponibles, historial previo de calidad, régimen regulatorio, perfil de volumen.',
    'Engineering review record, DFM/DFA recommendations with trade-off analysis, CTQ register, DFMEA where applicable, frozen technical baseline for APQP entry and supplier qualification.',
    'Registro de revisión de ingeniería, recomendaciones DFM/DFA con análisis de compensación, registro de CTQ, DFMEA cuando aplica, línea base técnica congelada para entrada a APQP y calificación de proveedores.',
    'Clarify intended use, regulatory regime, and any design intent decisions. Review and approve DFM recommendations and the frozen technical baseline before qualification and tooling commit.',
    'Aclarar uso previsto, régimen regulatorio y cualquier decisión de intención de diseño. Revisar y aprobar recomendaciones DFM y la línea base técnica congelada antes del compromiso de calificación y herramentales.',
  ),
  step(
    'supplier-qualification',
    'Supplier Qualification',
    'Calificación de Proveedores',
    'Match the requirement to qualified capability — assess process capability, quality system maturity, operational capacity, and program execution readiness against program-specific criteria.',
    'Relacionar el requisito con capacidad calificada — evaluar capacidad de proceso, madurez del sistema de calidad, capacidad operativa y preparación de ejecución de programa contra criterios específicos del programa.',
    'Process and quality requirements, tolerance class, regulatory regime, documentation expectations, volume and lead time profile.',
    'Requisitos de proceso y calidad, clase de tolerancia, régimen regulatorio, expectativas de documentación, perfil de volumen y plazo.',
    'Qualified execution route with documented evidence, supplier qualification record, FAI per AS9102-compatible format, PPAP submission at agreed level where applicable, surveillance plan for series production.',
    'Ruta de ejecución calificada con evidencia documentada, registro de calificación de proveedor, FAI en formato compatible con AS9102, presentación PPAP al nivel acordado cuando aplica, plan de vigilancia para producción en serie.',
    'Confirm acceptance criteria for FAI and PPAP. Review supplier qualification report and approve the supplier before production commitment.',
    'Confirmar criterios de aceptación para FAI y PPAP. Revisar el informe de calificación de proveedor y aprobar al proveedor antes del compromiso de producción.',
  ),
  step(
    'quotation',
    'Quotation & Award',
    'Cotización y Adjudicación',
    'Provide a transparent scope, lead time, and commercial basis — with assumptions, exclusions, and acceptance criteria explicit before award, not discovered after.',
    'Proporcionar alcance, plazo y base comercial transparentes — con supuestos, exclusiones y criterios de aceptación explícitos antes de la adjudicación, no descubiertos después.',
    'Approved scope statement, frozen technical baseline, qualified supplier(s), agreed acceptance criteria.',
    'Declaración de alcance aprobada, línea base técnica congelada, proveedor(es) calificado(s), criterios de aceptación acordados.',
    'Quotation with documented assumptions, lead time, commercial basis, payment terms, change-control process, and re-source triggers; basis of award documented after buyer decision.',
    'Cotización con supuestos documentados, plazo, base comercial, términos de pago, proceso de control de cambios y disparadores de re-abastecimiento; base de adjudicación documentada tras la decisión del comprador.',
    'Review scope, assumptions, and acceptance criteria before award. Confirm basis of award and authorize production release.',
    'Revisar alcance, supuestos y criterios de aceptación antes de la adjudicación. Confirmar la base de adjudicación y autorizar la liberación de producción.',
  ),
  step(
    'prototype',
    'Prototype & Validation',
    'Prototipo y Validación',
    'Validate critical design and process assumptions — apply design verification protocols, functional testing, and where applicable, customer application testing.',
    'Validar supuestos críticos de diseño y proceso — aplicar protocolos de verificación de diseño, pruebas funcionales y, cuando aplica, pruebas en aplicación del cliente.',
    'Released prototype scope, frozen technical baseline, validation protocols, agreed test plan.',
    'Alcance de prototipo liberado, línea base técnica congelada, protocolos de validación, plan de prueba acordado.',
    'Prototype samples, validation feedback, design iteration log where applicable, updated technical baseline if changes are approved.',
    'Muestras de prototipo, retroalimentación de validación, registro de iteración de diseño cuando aplica, línea base técnica actualizada si se aprueban cambios.',
    'Test samples in the intended application. Provide structured feedback. Approve or reject design iterations before production commit.',
    'Probar muestras en la aplicación prevista. Proporcionar retroalimentación estructurada. Aprobar o rechazar iteraciones de diseño antes del compromiso de producción.',
  ),
  step(
    'production',
    'Production & In-Process Control',
    'Producción y Control en Proceso',
    'Execute the approved production plan against the released control plan — in-process inspection, SPC where applicable, and supervision during critical operations.',
    'Ejecutar el plan de producción aprobado contra el plan de control liberado — inspección en proceso, SPC cuando aplica y supervisión durante operaciones críticas.',
    'Released drawings, BOM, control plan, tooling, qualified suppliers, production schedule.',
    'Planos liberados, BOM, plan de control, herramentales, proveedores calificados, cronograma de producción.',
    'Produced parts or assemblies with traceability, in-process inspection records, production batch records, escalation records for any deviations.',
    'Piezas o conjuntos producidos con trazabilidad, registros de inspección en proceso, registros de lote de producción, registros de escalamiento para cualquier desviación.',
    'Manage approved changes promptly through the change-control process. Review and disposition any nonconformances flagged during production.',
    'Gestionar cambios aprobados con prontitud a través del proceso de control de cambios. Revisar y disponer cualquier no conformidad marcada durante la producción.',
  ),
  step(
    'inspection',
    'Inspection & Release',
    'Inspección y Liberación',
    'Verify conformance before release — dimensional, visual, functional, and documentation verification against the agreed acceptance criteria.',
    'Verificar conformidad antes de liberar — verificación dimensional, visual, funcional y documental contra los criterios de aceptación acordados.',
    'Inspection plan, acceptance criteria, released product, inspection equipment (calibrated), inspection records template.',
    'Plan de inspección, criterios de aceptación, producto liberado, equipo de inspección (calibrado), plantilla de registros de inspección.',
    'Inspection record with measurement traceability, photographic evidence, functional test results, release status, disposition for any nonconformances.',
    'Registro de inspección con trazabilidad de medición, evidencia fotográfica, resultados de prueba funcional, estado de liberación, disposición para cualquier no conformidad.',
    'Review exceptions requiring disposition. Authorize shipment release for conforming product. Decide on rework, use-as-is, or scrap for nonconformances.',
    'Revisar excepciones que requieren disposición. Autorizar la liberación de envío para producto conforme. Decidir sobre retrabajo, uso tal cual o desecho para no conformidades.',
  ),
  step(
    'shipping',
    'Shipping & Documentation',
    'Envío y Documentación',
    'Deliver protected product with required documents — packaging specification, preservation, chain of custody, and complete documentation pack.',
    'Entregar producto protegido con documentos requeridos — especificación de embalaje, preservación, cadena de custodia y paquete documental completo.',
    'Released product, shipping instructions, packaging specification, documentation pack, customs and import requirements.',
    'Producto liberado, instrucciones de envío, especificación de embalaje, paquete documental, requisitos aduaneros y de importación.',
    'Shipment with chain of custody documentation, complete document pack (material certificates, inspection records, traceability, operating manuals as applicable), customs documentation.',
    'Envío con documentación de cadena de custodia, paquete documental completo (certificados de material, registros de inspección, trazabilidad, manuales de operación según aplique), documentación aduanera.',
    'Confirm receiving and import requirements. Acknowledge receipt and verify documentation completeness on arrival.',
    'Confirmar requisitos de recepción e importación. Acusar recibo y verificar completitud documental a la llegada.',
  ),
  step(
    'after-sales',
    'After-Sales & Continuity',
    'Posventa y Continuidad',
    'Maintain continuity for installed products and future requirements — field feedback integration, supplier performance monitoring, and spare-parts readiness.',
    'Mantener continuidad para productos instalados y requisitos futuros — integración de retroalimentación de campo, monitoreo de desempeño de proveedores y preparación de refacciones.',
    'Field feedback, service requirements, future forecast, supplier performance data, archived technical baseline.',
    'Retroalimentación de campo, requisitos de servicio, pronóstico futuro, datos de desempeño de proveedores, línea base técnica archivada.',
    'Support actions, improvement record, supplier performance report, updated technical baseline if changes are required, spare-parts availability confirmation.',
    'Acciones de soporte, registro de mejora, informe de desempeño de proveedor, línea base técnica actualizada si se requieren cambios, confirmación de disponibilidad de refacciones.',
    'Share operating feedback and forecasts. Authorize any engineering changes required for field issues. Confirm spare-parts requirements.',
    'Compartir retroalimentación operativa y pronósticos. Autorizar cualquier cambio de ingeniería requerido por problemas de campo. Confirmar requisitos de refacciones.',
  ),
];
