import type { LocalizedString, LocalizedStringArray } from './types';
const l = (en: string, es: string): LocalizedString => ({ en, es });
const a = (en: string[], es: string[]): LocalizedStringArray => ({ en, es });
export interface Resource { id: string; slug: LocalizedString; title: LocalizedString; description: LocalizedString; contents: LocalizedStringArray; }
export const resources: Resource[] = [
  { id: 'rfq-checklist', slug: l('rfq-checklist', 'lista-de-verificacion-rfq'), title: l('Industrial RFQ Checklist', 'Lista de verificación para RFQ industrial'), description: l('Prepare a request for quotation that suppliers can assess accurately.', 'Prepare una solicitud de cotización que los proveedores puedan evaluar con precisión.'), contents: a(['Application and quantities', 'Drawings and revision status', 'Materials and quality requirements', 'Commercial assumptions'], ['Aplicación y cantidades', 'Planos y estado de revisión', 'Materiales y requisitos de calidad', 'Supuestos comerciales']) },
  { id: 'supplier-audit-checklist', slug: l('supplier-audit-checklist', 'lista-de-verificacion-de-auditoria-de-proveedores'), title: l('Supplier Audit Checklist', 'Lista de verificación de auditoría de proveedores'), description: l('A practical framework for assessing production readiness and control.', 'Un marco práctico para evaluar preparación y control de producción.'), contents: a(['Quality system and records', 'Process capability', 'Equipment and maintenance', 'Corrective-action discipline'], ['Sistema de calidad y registros', 'Capacidad de proceso', 'Equipos y mantenimiento', 'Disciplina de acciones correctivas']) },
  { id: 'manufacturing-transfer-guide', slug: l('manufacturing-transfer-guide', 'guia-de-transferencia-de-manufactura'), title: l('Manufacturing Transfer Guide', 'Guía de transferencia de manufactura'), description: l('Plan a production move while preserving product and process knowledge.', 'Planifique un traslado de producción preservando el conocimiento de producto y proceso.'), contents: a(['Baseline technical package', 'Tooling and process readiness', 'Validation and first-production checks', 'Change-control governance'], ['Paquete técnico base', 'Preparación de herramentales y proceso', 'Validación y verificaciones de primera producción', 'Gobernanza de control de cambios']) },
  { id: 'drawing-package-requirements', slug: l('drawing-package-requirements', 'requisitos-del-paquete-de-planos'), title: l('Drawing Package Requirements', 'Requisitos del paquete de planos'), description: l('Define the information needed to manufacture and inspect a part consistently.', 'Defina la información necesaria para fabricar e inspeccionar una pieza de manera consistente.'), contents: a(['Dimensions and tolerances', 'Materials and finishes', 'Critical characteristics', 'Revision and approval information'], ['Dimensiones y tolerancias', 'Materiales y acabados', 'Características críticas', 'Información de revisión y aprobación']) },
];
