import type { LocalizedString, Service, ServiceGroup } from './types';

const l = (en: string, es: string): LocalizedString => ({ en, es });
const a = (en: string[], es: string[]) => ({ en, es });
const service = (id: string, enSlug: string, esSlug: string, enTitle: string, esTitle: string, enSummary: string, esSummary: string, group: ServiceGroup, enNeed: string, esNeed: string, enDeliverables: string[], esDeliverables: string[]): Service => ({
  id, slug: l(enSlug, esSlug), title: l(enTitle, esTitle), summary: l(enSummary, esSummary),
  description: l(`${enSummary} Our role is to create a clear, controlled path from technical intent to execution.`, `${esSummary} Nuestro papel es crear una ruta clara y controlada desde la intención técnica hasta la ejecución.`),
  whenNeeded: l(enNeed, esNeed),
  howWeExecute: l('We agree the scope, review the available inputs, coordinate responsible parties, and document decisions and controls.', 'Acordamos el alcance, revisamos los insumos disponibles, coordinamos a las partes responsables y documentamos decisiones y controles.'),
  deliverables: a(enDeliverables, esDeliverables), group,
});

export const services: Service[] = [
  service('engineering', 'engineering', 'ingenieria', 'Engineering', 'Ingeniería', 'Technical review and engineering coordination for manufacturable industrial products.', 'Revisión técnica y coordinación de ingeniería para productos industriales fabricables.', 'engineering', 'When requirements, drawings, or interfaces need technical clarification before execution.', 'Cuando los requisitos, planos o interfaces necesitan aclaración técnica antes de la ejecución.', ['Engineering review record', 'Manufacturability recommendations', 'Technical action register'], ['Registro de revisión de ingeniería', 'Recomendaciones de fabricabilidad', 'Registro de acciones técnicas']),
  service('supplier-qualification', 'supplier-qualification', 'calificacion-de-proveedores', 'Supplier Qualification', 'Calificación de proveedores', 'Assessment of manufacturing capability against a defined project requirement.', 'Evaluación de capacidad de manufactura frente a un requisito de proyecto definido.', 'quality', 'When production capability must be verified before a supplier is assigned.', 'Cuando la capacidad de producción debe verificarse antes de asignar un proveedor.', ['Capability assessment', 'Qualification criteria', 'Approved supplier recommendation'], ['Evaluación de capacidad', 'Criterios de calificación', 'Recomendación de proveedor aprobado']),
  service('project-management', 'project-management', 'gestion-de-proyectos', 'Project Management', 'Gestión de proyectos', 'Cross-functional coordination from project kick-off through delivery.', 'Coordinación multifuncional desde el inicio del proyecto hasta la entrega.', 'execution', 'When multiple technical, manufacturing, and logistics workstreams must stay aligned.', 'Cuando múltiples flujos técnicos, de manufactura y logística deben mantenerse alineados.', ['Project plan', 'Milestone reporting', 'Risk and action log'], ['Plan de proyecto', 'Reporte de hitos', 'Registro de riesgos y acciones']),
  service('quality-control', 'quality-control', 'control-de-calidad', 'Quality Control', 'Control de calidad', 'Inspection planning and verification against agreed requirements.', 'Planificación de inspección y verificación contra requisitos acordados.', 'quality', 'When conformance needs objective checks before shipment or acceptance.', 'Cuando la conformidad necesita verificaciones objetivas antes del envío o la aceptación.', ['Inspection plan', 'Inspection reports', 'Nonconformance follow-up'], ['Plan de inspección', 'Informes de inspección', 'Seguimiento de no conformidades']),
  service('manufacturing-supervision', 'manufacturing-supervision', 'supervision-de-manufactura', 'Manufacturing Supervision', 'Supervisión de manufactura', 'Execution oversight during critical production and assembly activities.', 'Supervisión de ejecución durante actividades críticas de producción y ensamblaje.', 'execution', 'When a build requires visibility beyond periodic inspection.', 'Cuando una fabricación requiere visibilidad más allá de la inspección periódica.', ['Production status report', 'Process observations', 'Escalation record'], ['Reporte de estado de producción', 'Observaciones de proceso', 'Registro de escalamiento']),
  service('product-development', 'product-development', 'desarrollo-de-producto', 'Product Development', 'Desarrollo de producto', 'Structured development from concept definition to production-ready specification.', 'Desarrollo estructurado desde la definición de concepto hasta la especificación lista para producción.', 'engineering', 'When a concept needs to become a manufacturable, documented product.', 'Cuando un concepto debe convertirse en un producto fabricable y documentado.', ['Product specification', 'Prototype plan', 'Production handover package'], ['Especificación de producto', 'Plan de prototipo', 'Paquete de transferencia a producción']),
  service('oem', 'oem', 'oem', 'OEM Manufacturing', 'Manufactura OEM', 'Contract manufacturing to a customer-owned design and specification.', 'Manufactura por contrato conforme a un diseño y especificación del cliente.', 'execution', 'When you own the design and need controlled production capacity.', 'Cuando usted posee el diseño y necesita capacidad de producción controlada.', ['Manufacturing plan', 'Production records', 'Configured product delivery'], ['Plan de manufactura', 'Registros de producción', 'Entrega de producto configurado']),
  service('odm', 'odm', 'odm', 'ODM Development', 'Desarrollo ODM', 'Adaptable product development using proven platforms and manufacturing knowledge.', 'Desarrollo adaptable de productos usando plataformas probadas y conocimiento de manufactura.', 'engineering', 'When a market need can be met by adapting an existing technical platform.', 'Cuando una necesidad de mercado puede atenderse adaptando una plataforma técnica existente.', ['Adaptation proposal', 'Technical specification', 'Validation plan'], ['Propuesta de adaptación', 'Especificación técnica', 'Plan de validación']),
  service('reverse-engineering', 'reverse-engineering', 'ingenieria-inversa', 'Reverse Engineering', 'Ingeniería inversa', 'Technical reconstruction of legacy or unavailable components for defined use.', 'Reconstrucción técnica de componentes heredados o no disponibles para un uso definido.', 'engineering', 'When a replacement part lacks complete drawings or technical data.', 'Cuando una pieza de reemplazo carece de planos completos o datos técnicos.', ['Measured data set', 'Reconstructed drawing', 'Replacement-part recommendation'], ['Conjunto de datos medidos', 'Plano reconstruido', 'Recomendación de pieza de reemplazo']),
  service('tooling', 'tooling', 'herramentales', 'Tooling', 'Herramentales', 'Design coordination and controlled build of production tooling and fixtures.', 'Coordinación de diseño y construcción controlada de herramentales y dispositivos de producción.', 'engineering', 'When repeatable production depends on a dedicated mold, die, jig, or fixture.', 'Cuando la producción repetible depende de un molde, troquel, plantilla o dispositivo dedicado.', ['Tooling specification', 'Trial report', 'Tool acceptance record'], ['Especificación de herramental', 'Informe de pruebas', 'Registro de aceptación de herramental']),
  service('manufacturing-transfer', 'manufacturing-transfer', 'transferencia-de-manufactura', 'Manufacturing Transfer', 'Transferencia de manufactura', 'Orderly migration of production between sites, suppliers, or regions.', 'Migración ordenada de producción entre plantas, proveedores o regiones.', 'execution', 'When a product must move without losing process knowledge or quality controls.', 'Cuando un producto debe trasladarse sin perder conocimiento de proceso ni controles de calidad.', ['Transfer plan', 'Readiness review', 'First-production verification'], ['Plan de transferencia', 'Revisión de preparación', 'Verificación de primera producción']),
  service('factory-audits', 'factory-audits', 'auditorias-de-fabrica', 'Factory Audits', 'Auditorías de fábrica', 'On-site or remote assessment of manufacturing systems and project readiness.', 'Evaluación presencial o remota de sistemas de manufactura y preparación de proyecto.', 'quality', 'When you need evidence of process capability, controls, and operational maturity.', 'Cuando necesita evidencia de capacidad de proceso, controles y madurez operativa.', ['Audit checklist', 'Findings report', 'Corrective-action follow-up'], ['Lista de verificación de auditoría', 'Informe de hallazgos', 'Seguimiento de acciones correctivas']),
  service('supply-chain-development', 'supply-chain-development', 'desarrollo-de-cadena-de-suministro', 'Supply Chain Development', 'Desarrollo de cadena de suministro', 'Development of a resilient, qualified manufacturing ecosystem for a product family.', 'Desarrollo de un ecosistema de manufactura resiliente y calificado para una familia de productos.', 'supply-chain', 'When supply continuity depends on more than one process, supplier, or region.', 'Cuando la continuidad de suministro depende de más de un proceso, proveedor o región.', ['Supply chain map', 'Qualification plan', 'Continuity recommendations'], ['Mapa de cadena de suministro', 'Plan de calificación', 'Recomendaciones de continuidad']),
  service('strategic-sourcing', 'strategic-sourcing', 'sourcing-estrategico', 'Strategic Sourcing', 'Sourcing estratégico', 'Structured supplier and cost strategy for defined industrial requirements.', 'Estrategia estructurada de proveedores y costos para requisitos industriales definidos.', 'supply-chain', 'When a category needs a technically informed sourcing strategy, not a simple price comparison.', 'Cuando una categoría necesita una estrategia de abastecimiento técnicamente informada, no una simple comparación de precios.', ['Sourcing strategy', 'Supplier comparison', 'Negotiation and award recommendation'], ['Estrategia de abastecimiento', 'Comparación de proveedores', 'Recomendación de negociación y adjudicación']),
  service('nearshoring-support', 'nearshoring-support', 'soporte-de-nearshoring', 'Nearshoring Support', 'Soporte de Nearshoring', 'Manufacturing setup, supplier qualification, and production transfer support for companies relocating operations from Asia to Latin America — particularly Mexico and Central America.', 'Configuración de manufactura, calificación de proveedores y soporte de transferencia de producción para empresas que relocalizan operaciones de Asia a América Latina — particularmente México y Centroamérica.', 'supply-chain', 'When a company is evaluating or executing a move of production capability from Asia to Latin America and needs technical qualification, transfer control, and supplier readiness.', 'Cuando una empresa está evaluando o ejecutando el traslado de capacidad productiva de Asia a América Latina y necesita calificación técnica, control de transferencia y preparación de proveedores.', ['Nearshoring readiness assessment', 'Supplier qualification plan', 'Transfer and ramp-up roadmap', 'Quality and documentation handover package'], ['Evaluación de preparación para nearshoring', 'Plan de calificación de proveedores', 'Hoja de ruta de transferencia y ramp-up', 'Paquete de entrega de calidad y documentación']),
];
