import type { LocalizedString, Service, ServiceGroup } from './types';

const l = (en: string, es: string): LocalizedString => ({ en, es });
const a = (en: string[], es: string[]): { en: string[]; es: string[] } => ({ en, es });

const service = (
  id: string,
  enSlug: string,
  esSlug: string,
  enTitle: string,
  esTitle: string,
  enSummary: string,
  esSummary: string,
  group: ServiceGroup,
  enDescription: string,
  esDescription: string,
  enNeed: string,
  esNeed: string,
  enHowWeExecute: string,
  esHowWeExecute: string,
  enDeliverables: string[],
  esDeliverables: string[],
): Service => ({
  id,
  slug: l(enSlug, esSlug),
  title: l(enTitle, esTitle),
  summary: l(enSummary, esSummary),
  description: l(enDescription, esDescription),
  whenNeeded: l(enNeed, esNeed),
  howWeExecute: l(enHowWeExecute, esHowWeExecute),
  deliverables: a(enDeliverables, esDeliverables),
  group,
});

export const services: Service[] = [
  service(
    'engineering',
    'engineering',
    'ingenieria',
    'Engineering Review & Technical Coordination',
    'Revisión de Ingeniería y Coordinación Técnica',
    'Structured technical review of drawings, specifications, tolerances, materials, and process fit before production commitment — converting intent into a manufacturable, inspectable technical package.',
    'Revisión técnica estructurada de planos, especificaciones, tolerancias, materiales y ajuste de proceso antes del compromiso de producción — convirtiendo la intención en un paquete técnico fabricable e inspeccionable.',
    'engineering',
    'Engineering review is the technical gate between product intent and production reality. Before any tooling, qualification, or quotation is committed, we analyze the input package — drawings, CAD models, BOM, material specifications, GD&T, cosmetic standards, and intended use — against the capabilities of candidate manufacturing processes. We surface manufacturability risks that would otherwise surface later as cost overruns, schedule slippage, or nonconformance. The output is an engineering review record that captures assumptions, open technical items, recommended design changes (Design for Manufacturability / Design for Assembly — DFM/DFA), and a clear definition of critical-to-quality (CTQ) characteristics. This work aligns the program team, the supplier, and the inspection function around a single technical baseline, and forms the input for supplier qualification, tooling, and PPAP/APQP planning.',
    'La revisión de ingeniería es la puerta técnica entre la intención del producto y la realidad de producción. Antes de comprometer herramentales, calificación o cotización, analizamos el paquete de entrada — planos, modelos CAD, BOM, especificaciones de material, GD&T, estándares estéticos y uso previsto — frente a las capacidades de los procesos de manufactura candidatos. Detectamos riesgos de fabricabilidad que de otro modo surgirían más adelante como sobrecostos, retrasos o no conformidades. La salida es un registro de revisión de ingeniería que captura supuestos, ítems técnicos abiertos, cambios de diseño recomendados (Diseño para Manufacturabilidad / Diseño para Ensamble — DFM/DFA) y una definición clara de las características críticas para la calidad (CTQ). Este trabajo alinea al equipo del programa, al proveedor y a la función de inspección en una sola línea base técnica, y forma la entrada para la calificación de proveedores, herramentales y la planificación de PPAP/APQP.',
    'When drawings, tolerances, materials, or interfaces carry technical risk that must be resolved before tooling, qualification, or quotation. Typical triggers: incomplete technical packages, legacy parts without current documentation, multi-process assemblies, imported designs that must be localized to Asian manufacturing capability, or components with critical cosmetic, dimensional, or regulatory requirements.',
    'Cuando los planos, tolerancias, materiales o interfaces conllevan riesgo técnico que debe resolverse antes de herramentales, calificación o cotización. Disparadores típicos: paquetes técnicos incompletos, piezas heredadas sin documentación actual, conjuntos multiproceso, diseños importados que deben localizarse a la capacidad de manufactura asiática, o componentes con requisitos estéticos, dimensionales o regulatorios críticos.',
    'We open a controlled technical review with a structured checklist: drawing completeness and revision control, tolerance stack-up against process capability (Cpk/Ppk targets), material selection and availability in the region, surface finish and cosmetic specifications, assembly sequence, inspection method feasibility, and packaging/handling constraints. Open items are logged with owner and due date. Where DFM/DFA improvements are identified, we document the recommendation with rationale and estimated impact on cost, lead time, and quality. The review concludes with a frozen technical baseline signed off by the program team — the foundation for APQP entry, tooling kickoff, and supplier selection.',
    'Abrimos una revisión técnica controlada con una lista estructurada: integridad del plano y control de revisión, análisis de tolerancias frente a capacidad de proceso (Cpk/Ppk objetivo), selección y disponibilidad de material en la región, acabado superficial y especificaciones estéticas, secuencia de ensamblaje, factibilidad del método de inspección y restricciones de embalaje/manejo. Los ítems abiertos se registran con responsable y fecha. Cuando se identifican mejoras DFM/DFA, se documentan con justificación y el impacto estimado en costo, plazo y calidad. La revisión concluye con una línea base técnica congelada y firmada por el equipo del programa — la base para la entrada a APQP, arranque de herramentales y selección de proveedores.',
    [
      'Engineering review record with documented assumptions',
      'Manufacturability (DFM/DFA) recommendations and trade-off analysis',
      'Critical-to-Quality (CTQ) characteristic register',
      'Open technical item log with owners and due dates',
      'Frozen technical baseline for APQP entry',
    ],
    [
      'Registro de revisión de ingeniería con supuestos documentados',
      'Recomendaciones de fabricabilidad (DFM/DFA) y análisis de compromiso',
      'Registro de características críticas para la calidad (CTQ)',
      'Bitácora de ítems técnicos abiertos con responsables y fechas',
      'Línea base técnica congelada para entrada a APQP',
    ],
  ),
  service(
    'supplier-qualification',
    'supplier-qualification',
    'calificacion-de-proveedores',
    'Supplier Qualification',
    'Calificación de Proveedores',
    'Evidence-based assessment of manufacturing capability, quality system maturity, and capacity against the specific requirements of a defined project — not a generic audit.',
    'Evaluación basada en evidencia de la capacidad de manufactura, madurez del sistema de calidad y capacidad productiva frente a los requisitos específicos de un proyecto definido — no una auditoría genérica.',
    'quality',
    'Supplier qualification is the process by which we establish, with documented evidence, that a candidate manufacturer can repeatedly produce a part or assembly to the project\'s technical, quality, and delivery requirements. It is not a one-time factory tour or a generic audit certificate — it is a structured evaluation tailored to the specific process, material, tolerance, and volume profile of the program. We assess four dimensions in parallel: process capability (equipment, tooling, process route), quality system maturity (ISO 9001 / IATF 16949 / ISO 13485 alignment, control plans, MSA, calibration), operational capacity (capacity loading, lead time, second-source resilience), and commercial/program execution (project management, change control, escalation paths). The output is a qualification record that defines the conditions under which the supplier is approved, the residual risks accepted, and the surveillance plan applied during series production.',
    'La calificación de proveedores es el proceso por el cual establecemos, con evidencia documentada, que un fabricante candidato puede producir repetidamente una pieza o conjunto conforme a los requisitos técnicos, de calidad y de entrega del proyecto. No es una visita única a la fábrica ni un certificado de auditoría genérico — es una evaluación estructurada adaptada al proceso, material, tolerancia y perfil de volumen específicos del programa. Evaluamos cuatro dimensiones en paralelo: capacidad de proceso (equipo, herramentales, ruta de proceso), madurez del sistema de calidad (alineación ISO 9001 / IATF 16949 / ISO 13485, planes de control, MSA, calibración), capacidad operativa (carga de capacidad, plazo, resiliencia de segunda fuente) y ejecución comercial/programa (gestión de proyectos, control de cambios, rutas de escalamiento). La salida es un registro de calificación que define las condiciones bajo las cuales el proveedor se aprueba, los riesgos residuales aceptados y el plan de vigilancia aplicado durante la producción en serie.',
    'When production capability must be verified before a supplier is awarded business — new product introduction (NPI), manufacturing transfer, second-source qualification, or any program where process risk cannot be retired by inspection alone. Also required when existing supplier capability must be re-verified after significant volume, design, or ownership changes.',
    'Cuando la capacidad de producción debe verificarse antes de adjudicar trabajo a un proveedor — introducción de nuevo producto (NPI), transferencia de manufactura, calificación de segunda fuente, o cualquier programa donde el riesgo de proceso no pueda resolverse solo con inspección. También se requiere cuando la capacidad de un proveedor existente debe reverificarse tras cambios significativos de volumen, diseño o propiedad.',
    'Qualification begins with a scoping document that defines the requirements against which the supplier will be measured — process route, tolerance class, volume range, regulatory regime, documentation expectations. We then execute a structured on-site (or hybrid remote) assessment covering equipment capability, process flow, PFMEA review, control plan, MSA / Gage R&R status, calibration system, traceability practices, and operator training. Where the qualification requires production evidence, we run a first-article inspection (FAI, AS9102-compatible) and, where applicable, a PPAP submission at the level agreed with the customer. Findings are categorized by severity; corrective actions are tracked to closure before production authorization.',
    'La calificación comienza con un documento de alcance que define los requisitos frente a los cuales se medirá al proveedor — ruta de proceso, clase de tolerancia, rango de volumen, régimen regulatorio y expectativas de documentación. Luego ejecutamos una evaluación estructurada in situ (o híbrida remota) que cubre capacidad de equipo, flujo de proceso, revisión de PFMEA, plan de control, estado de MSA / Gage R&R, sistema de calibración, prácticas de trazabilidad y capacitación de operadores. Cuando la calificación requiere evidencia de producción, ejecutamos una inspección de primer artículo (FAI, compatible con AS9102) y, cuando aplica, una presentación PPAP en el nivel acordado con el cliente. Los hallazgos se categorizan por severidad; las acciones correctivas se rastrean hasta su cierre antes de la autorización de producción.',
    [
      'Supplier qualification record with scope and acceptance criteria',
      'Process capability assessment (Cpk/Ppk where applicable)',
      'Quality system alignment report (ISO 9001 / IATF 16949 / ISO 13485)',
      'First-article inspection (FAI) per AS9102-compatible format',
      'PPAP submission package at agreed level (where applicable)',
      'Approved supplier list entry with conditions and surveillance plan',
    ],
    [
      'Registro de calificación de proveedor con alcance y criterios de aceptación',
      'Evaluación de capacidad de proceso (Cpk/Ppk cuando aplica)',
      'Informe de alineación del sistema de calidad (ISO 9001 / IATF 16949 / ISO 13485)',
      'Inspección de primer artículo (FAI) en formato compatible con AS9102',
      'Paquete de presentación PPAP al nivel acordado (cuando aplica)',
      'Entrada en lista de proveedores aprobados con condiciones y plan de vigilancia',
    ],
  ),
  service(
    'project-management',
    'project-management',
    'gestion-de-proyectos',
    'Industrial Project Management',
    'Gestión de Proyectos Industriales',
    'Cross-functional program execution from kick-off through delivery — managing engineering, supplier, quality, and logistics workstreams against a single integrated schedule.',
    'Ejecución multifuncional de programa desde el arranque hasta la entrega — gestionando ingeniería, proveedor, calidad y logística contra un solo cronograma integrado.',
    'execution',
    'Industrial projects rarely fail at a single point — they drift when engineering decisions, supplier readiness, quality verification, and logistics sequencing are not held against a common baseline. Our project management function integrates these workstreams into a single program plan with defined milestones, owners, and exit criteria. We work to industrial program execution standards: a work breakdown structure (WBS) that maps deliverables to activities, an integrated master schedule (IMS) that surfaces dependencies and the critical path, a risk register that is reviewed at every gate, and a change-control process that prevents scope drift from corrupting the technical baseline. Reporting is structured around milestone status, risk burn-down, open technical items, and supplier readiness — the four signals that determine whether a program will deliver on time and on spec.',
    'Los proyectos industriales rara vez fallan en un solo punto — se desvían cuando las decisiones de ingeniería, la preparación del proveedor, la verificación de calidad y la secuencia logística no se mantienen contra una línea base común. Nuestra función de gestión de proyectos integra estos flujos de trabajo en un solo plan de programa con hitos, responsables y criterios de salida definidos. Trabajamos según estándares de ejecución de programas industriales: una estructura de desglose de trabajo (WBS) que mapea entregables a actividades, un cronograma maestro integrado (IMS) que expone dependencias y la ruta crítica, un registro de riesgos que se revisa en cada puerta, y un proceso de control de cambios que evita que la deriva de alcance corrompa la línea base técnica. Los reportes se estructuran alrededor del estado de hitos, la reducción de riesgo, los ítems técnicos abiertos y la preparación del proveedor — las cuatro señales que determinan si un programa entregará a tiempo y bajo especificación.',
    'When multiple technical, manufacturing, quality, and logistics workstreams must stay aligned — NPI programs, multi-supplier assemblies, manufacturing transfers, equipment build packages, or any project where a delay in one stream cascades into others. Particularly valuable when the program spans multiple regions or when the buyer cannot maintain full-time on-site presence at the supplier.',
    'Cuando múltiples flujos de trabajo técnicos, de manufactura, de calidad y logística deben permanecer alineados — programas NPI, conjuntos multiproveedor, transferencias de manufactura, paquetes de construcción de equipos, o cualquier proyecto donde un retraso en un flujo se propague a otros. Particularmente valioso cuando el programa abarca múltiples regiones o cuando el comprador no puede mantener presencia total en sitio del proveedor.',
    'We establish a program charter, scope statement, and WBS at kick-off, then build an IMS that links engineering releases, tooling milestones, FAI/PPAP gates, production ramp, and logistics windows. Each milestone has explicit exit criteria. A risk register is opened at kick-off and reviewed weekly — each risk carries a probability, impact, mitigation owner, and contingency trigger. A RACI matrix defines decision rights across the buyer, our team, and the supplier. Status reporting follows a fixed cadence (weekly operational, monthly executive) and uses milestone-completion-based progress rather than subjective percent-complete. All changes flow through a documented change-control process that updates the technical baseline and the affected schedule and cost.',
    'Establecemos una carta de programa, declaración de alcance y WBS en el arranque, luego construimos un IMS que vincula liberaciones de ingeniería, hitos de herramentales, puertas FAI/PPAP, rampa de producción y ventanas logísticas. Cada hito tiene criterios de salida explícitos. Se abre un registro de riesgos al arranque y se revisa semanalmente — cada riesgo tiene probabilidad, impacto, responsable de mitigación y disparador de contingencia. Una matriz RACI define los derechos de decisión entre comprador, nuestro equipo y el proveedor. Los reportes de estado siguen una cadencia fija (semanal operacional, mensual ejecutiva) y usan progreso basado en cumplimiento de hitos, no porcentaje subjetivo de avance. Todos los cambios fluyen por un proceso de control de cambios documentado que actualiza la línea base técnica y el cronograma y costo afectados.',
    [
      'Program charter, scope statement, and WBS',
      'Integrated master schedule (IMS) with critical path and milestones',
      'Risk register with mitigation owners and contingency triggers',
      'RACI matrix across buyer, Top Industrial, and supplier',
      'Weekly operational and monthly executive status reports',
      'Documented engineering change control process',
    ],
    [
      'Carta de programa, declaración de alcance y WBS',
      'Cronograma maestro integrado (IMS) con ruta crítica y hitos',
      'Registro de riesgos con responsables de mitigación y disparadores de contingencia',
      'Matriz RACI entre comprador, Top Industrial y proveedor',
      'Reportes de estado operacionales semanales y ejecutivos mensuales',
      'Proceso documentado de control de cambios de ingeniería',
    ],
  ),
  service(
    'quality-control',
    'quality-control',
    'control-de-calidad',
    'Quality Control & Inspection',
    'Control de Calidad e Inspección',
    'Inspection planning and execution aligned to drawings, standards, and agreed acceptance criteria — dimensional, visual, functional, and documentation verification across the production lifecycle.',
    'Planificación y ejecución de inspección alineada a planos, estándares y criterios de aceptación acordados — verificación dimensional, visual, funcional y documental a lo largo del ciclo de producción.',
    'quality',
    'Quality control is the objective verification that produced parts and assemblies conform to the technical baseline. We design inspection plans that match the risk profile of the part: every CTQ dimension is verified, sampling is risk-based (not arbitrary AQL), and acceptance criteria are defined before the first part is produced. We operate across four inspection modes: incoming inspection of supplier components, in-process inspection during production, first-article inspection (FAI) at process launch, and final/pre-shipment inspection. Inspection records include dimensional data with measurement traceability, photographic evidence of visual and cosmetic conditions, functional test results, and disposition status. Where nonconformances are detected, we trigger a documented disposition process — sort, rework, use-as-is, or scrap — followed by root-cause analysis and corrective action (8D methodology where applicable).',
    'El control de calidad es la verificación objetiva de que las piezas y conjuntos producidos cumplen la línea base técnica. Diseñamos planes de inspección que coinciden con el perfil de riesgo de la pieza: toda dimensión CTQ se verifica, el muestreo se basa en riesgo (no AQL arbitrario), y los criterios de aceptación se definen antes de producir la primera pieza. Operamos en cuatro modos de inspección: inspección de entrada de componentes del proveedor, inspección en proceso durante la producción, inspección de primer artículo (FAI) en el lanzamiento del proceso, e inspección final/previa al envío. Los registros de inspección incluyen datos dimensionales con trazabilidad de medición, evidencia fotográfica de condiciones estéticas y visuales, resultados de pruebas funcionales y estado de disposición. Cuando se detectan no conformidades, disparamos un proceso de disposición documentado — clasificar, retrabajar, usar tal cual o desechar — seguido de análisis de causa raíz y acción correctiva (metodología 8D cuando aplica).',
    'When conformance needs objective verification before shipment, acceptance, or assembly — first-article inspections, in-process surveillance, pre-shipment inspections (PSI), critical-to-quality (CTQ) verification, or any program where the cost of a defect reaching the next stage is significantly higher than the cost of inspection.',
    'Cuando la conformidad necesita verificación objetiva antes del envío, aceptación o ensamblaje — inspecciones de primer artículo, vigilancia en proceso, inspecciones previas al envío (PSI), verificación de características críticas para la calidad (CTQ), o cualquier programa donde el costo de un defecto que llega a la siguiente etapa sea significativamente mayor que el costo de inspección.',
    'We develop an inspection plan per part number, derived from the technical baseline and CTQ register. The plan defines the inspection mode (incoming, in-process, FAI, final), the characteristics to be verified with acceptance criteria, the sampling plan (risk-based, AQL, or 100% for CTQs), the measurement equipment and method, and the documentation to be produced. Inspection is executed by qualified inspectors using calibrated equipment with traceable standards. Results are recorded with measurement uncertainty where applicable. Nonconformances are dispositioned through a Material Review Board (MRB) process; corrective actions follow the 8D methodology with verification of effectiveness before closure.',
    'Desarrollamos un plan de inspección por número de parte, derivado de la línea base técnica y el registro CTQ. El plan define el modo de inspección (entrada, en proceso, FAI, final), las características a verificar con criterios de aceptación, el plan de muestreo (basado en riesgo, AQL o 100% para CTQs), el equipo y método de medición, y la documentación a producir. La inspección la ejecutan inspectores calificados usando equipos calibrados con estándares trazables. Los resultados se registran con incertidumbre de medición cuando aplica. Las no conformidades se disponen por un proceso de Junta de Revisión de Material (MRB); las acciones correctivas siguen la metodología 8D con verificación de efectividad antes del cierre.',
    [
      'Inspection plan per part number with CTQ identification',
      'First-article inspection (FAI) report — AS9102-compatible format',
      'In-process inspection records with measurement traceability',
      'Pre-shipment inspection (PSI) report with photographic evidence',
      'Nonconformance disposition record and 8D corrective action log',
      'Statistical process control (SPC) data where applicable',
    ],
    [
      'Plan de inspección por número de parte con identificación de CTQ',
      'Informe de inspección de primer artículo (FAI) — formato compatible con AS9102',
      'Registros de inspección en proceso con trazabilidad de medición',
      'Informe de inspección previa al envío (PSI) con evidencia fotográfica',
      'Registro de disposición de no conformidad y bitácora de acción correctiva 8D',
      'Datos de control estadístico de proceso (SPC) cuando aplica',
    ],
  ),
  service(
    'manufacturing-supervision',
    'manufacturing-supervision',
    'supervision-de-manufactura',
    'Manufacturing Supervision',
    'Supervisión de Manufactura',
    'On-site execution oversight during critical production activities — first builds, qualification runs, ramp-up, and any process where visibility beyond periodic inspection is required.',
    'Supervisión de ejecución en sitio durante actividades críticas de producción — primeras construcciones, corridas de calificación, ramp-up y cualquier proceso donde se requiera visibilidad más allá de la inspección periódica.',
    'execution',
    'Manufacturing supervision provides direct visibility and intervention during the moments when a production program is most vulnerable: the first build, the qualification run, the ramp-up phase, or any operation where the risk of drift, misinterpretation, or silent nonconformance is high. Our supervisors work on the supplier floor as the buyer\'s eyes and ears — observing setup, monitoring in-process parameters against the control plan, verifying first-off parts, escalating deviations in real time, and capturing process observations that do not appear in inspection reports. The objective is not to replace the supplier\'s own quality function, but to provide an independent, technically informed presence that closes the gap between the buyer\'s intent and the supplier\'s execution — particularly valuable when the buyer is geographically remote and the program carries technical or commercial risk.',
    'La supervisión de manufactura proporciona visibilidad e intervención directa durante los momentos en que un programa de producción es más vulnerable: la primera construcción, la corrida de calificación, la fase de ramp-up, o cualquier operación donde el riesgo de deriva, mala interpretación o no conformidad silenciosa es alto. Nuestros supervisores trabajan en el piso del proveedor como ojos y oídos del comprador — observando la preparación, monitoreando parámetros en proceso contra el plan de control, verificando primeras piezas, escalando desviaciones en tiempo real y capturando observaciones de proceso que no aparecen en informes de inspección. El objetivo no es reemplazar la función de calidad del proveedor, sino proporcionar una presencia independiente y técnicamente informada que cierre la brecha entre la intención del comprador y la ejecución del proveedor — particularmente valioso cuando el comprador está geográficamente alejado y el programa conlleva riesgo técnico o comercial.',
    'When a build requires visibility beyond periodic inspection — first-article builds, qualification runs (PPAP / PSW), ramp-up phases, processes with known variability, cosmetic-critical operations, or any situation where early detection of drift prevents large-volume nonconformance. Especially valuable when the buyer cannot be on-site and needs a technically literate representative.',
    'Cuando una construcción requiere visibilidad más allá de la inspección periódica — primeras construcciones, corridas de calificación (PPAP / PSW), fases de ramp-up, procesos con variabilidad conocida, operaciones estéticamente críticas, o cualquier situación donde la detección temprana de deriva prevenga no conformidades en gran volumen. Especialmente valioso cuando el comprador no puede estar en sitio y necesita un representante técnicamente alfabetizado.',
    'Supervision is planned around the supplier\'s production schedule and the program\'s risk profile. We attend machine setup, verify first-off parts against the control plan, monitor in-process parameters (cycle time, temperatures, pressures, torques as applicable), perform in-process inspections at the agreed frequency, and document observations in a shift report. Deviations are escalated through a defined path with named decision rights. Where issues arise, we facilitate immediate root-cause discussion between the supplier\'s technical staff and the buyer rather than waiting for the next inspection cycle. A daily situation report and a weekly executive summary keep all stakeholders aligned without overwhelming the program team.',
    'La supervisión se planifica alrededor del cronograma de producción del proveedor y el perfil de riesgo del programa. Asistimos a la preparación de máquina, verificamos primeras piezas contra el plan de control, monitoreamos parámetros en proceso (tiempo de ciclo, temperaturas, presiones, torques según aplique), realizamos inspecciones en proceso en la frecuencia acordada y documentamos observaciones en un reporte de turno. Las desviaciones se escalan por una ruta definida con derechos de decisión nombrados. Cuando surgen problemas, facilitamos discusión inmediata de causa raíz entre el personal técnico del proveedor y el comprador en lugar de esperar al siguiente ciclo de inspección. Un reporte diario de situación y un resumen ejecutivo semanal mantienen a todos los interesados alineados sin abrumar al equipo del programa.',
    [
      'Supervision plan aligned with supplier production schedule',
      'Daily shift report with process observations',
      'In-process inspection records during supervision window',
      'Real-time escalation record for deviations',
      'Weekly executive summary with risk indicators',
      'Photographic documentation of critical operations',
    ],
    [
      'Plan de supervisión alineado con el cronograma de producción del proveedor',
      'Reporte diario de turno con observaciones de proceso',
      'Registros de inspección en proceso durante la ventana de supervisión',
      'Registro de escalamiento en tiempo real para desviaciones',
      'Resumen ejecutivo semanal con indicadores de riesgo',
      'Documentación fotográfica de operaciones críticas',
    ],
  ),
  service(
    'product-development',
    'product-development',
    'desarrollo-de-producto',
    'Product Development (NPI)',
    'Desarrollo de Producto (NPI)',
    'Structured new product development from concept definition through production-ready specification — applying APQP, DFM/DFA, and validation planning to convert market need into a manufacturable product.',
    'Desarrollo estructurado de nuevo producto desde la definición de concepto hasta la especificación lista para producción — aplicando APQP, DFM/DFA y planificación de validación para convertir una necesidad de mercado en un producto fabricable.',
    'engineering',
    'Product development at the industrial level is not sketching — it is a structured conversion of market and functional requirements into a manufacturable, inspectable, and serviceable product. We apply Advanced Product Quality Planning (APQP) as the backbone: phase 0 (voice of customer / concept), phase 1 (product design), phase 2 (process design), phase 3 (product and process validation), phase 4 (launch and ramp-up), with formal gate reviews between phases. Within that framework, we execute Design for Manufacturability and Assembly (DFM/DFA) analysis, tolerance stack-up studies, material selection against the operating environment, and DFMEA (Design FMEA) to anticipate failure modes before they are designed in. The output is a production-ready technical package — drawings, BOM, specifications, validation plan, and tooling specification — that hands off to a qualified supplier with clear acceptance criteria.',
    'El desarrollo de producto a nivel industrial no es bocetar — es una conversión estructurada de requisitos de mercado y funcionales en un producto fabricable, inspeccionable y servible. Aplicamos Planificación Avanzada de la Calidad del Producto (APQP) como columna vertebral: fase 0 (voz del cliente / concepto), fase 1 (diseño del producto), fase 2 (diseño del proceso), fase 3 (validación de producto y proceso), fase 4 (lanzamiento y ramp-up), con revisiones formales de puerta entre fases. Dentro de ese marco, ejecutamos análisis de Diseño para Manufacturabilidad y Ensamble (DFM/DFA), estudios de apilamiento de tolerancias, selección de material contra el entorno operativo, y DFMEA (FMEA de Diseño) para anticipar modos de falla antes de que se diseñen. La salida es un paquete técnico listo para producción — planos, BOM, especificaciones, plan de validación y especificación de herramentales — que se entrega a un proveedor calificado con criterios de aceptación claros.',
    'When a concept needs to become a manufacturable, documented product — new product introduction (NPI), redesign for cost reduction, design for regulatory compliance, or adaptation of an existing platform to a new market. Particularly applicable when the buyer\'s design team lacks manufacturing process knowledge or when a product is being developed for production in Asia for the first time.',
    'Cuando un concepto debe convertirse en un producto fabricable y documentado — introducción de nuevo producto (NPI), rediseño para reducción de costos, diseño para cumplimiento regulatorio, o adaptación de una plataforma existente a un nuevo mercado. Particularmente aplicable cuando el equipo de diseño del comprador carece de conocimiento del proceso de manufactura o cuando un producto se desarrolla para producción en Asia por primera vez.',
    'We begin with a Product Definition document — functional requirements, operating environment, regulatory regime, target cost, volume profile, and serviceability expectations. From there we work through APQP phases: concept design with DFM/DFA analysis, detailed design with tolerance studies and DFMEA, process design with PFMEA and control plan, validation planning (design verification and product validation protocols), and launch planning including ramp-up schedule and after-sales readiness. Each phase ends with a gate review where the technical baseline is updated and the program is authorized to proceed. We coordinate closely with the selected manufacturing partner throughout — they participate in DFM reviews and contribute process knowledge that improves the design before tooling is committed.',
    'Comenzamos con un Documento de Definición de Producto — requisitos funcionales, entorno operativo, régimen regulatorio, costo objetivo, perfil de volumen y expectativas de servibilidad. Desde ahí trabajamos por las fases APQP: diseño conceptual con análisis DFM/DFA, diseño detallado con estudios de tolerancia y DFMEA, diseño de proceso con PFMEA y plan de control, planificación de validación (protocolos de verificación de diseño y validación de producto), y planificación de lanzamiento incluyendo cronograma de ramp-up y preparación posventa. Cada fase termina con una revisión de puerta donde se actualiza la línea base técnica y se autoriza al programa a continuar. Coordinamos estrechamente con el socio de manufactura seleccionado durante todo el proceso — participan en revisiones DFM y aportan conocimiento de proceso que mejora el diseño antes de comprometer herramentales.',
    [
      'Product definition document with functional and regulatory requirements',
      'APQP phase-gate plan with review checkpoints',
      'DFM/DFA analysis with cost and manufacturability trade-offs',
      'Tolerance stack-up study and DFMEA report',
      'Process design with PFMEA and control plan',
      'Production-ready technical package (drawings, BOM, specs, validation plan)',
    ],
    [
      'Documento de definición de producto con requisitos funcionales y regulatorios',
      'Plan de puertas de fase APQP con puntos de revisión',
      'Análisis DFM/DFA con compensaciones de costo y fabricabilidad',
      'Estudio de apilamiento de tolerancias e informe DFMEA',
      'Diseño de proceso con PFMEA y plan de control',
      'Paquete técnico listo para producción (planos, BOM, especificaciones, plan de validación)',
    ],
  ),
  service(
    'oem',
    'oem',
    'oem',
    'OEM Contract Manufacturing',
    'Manufactura OEM por Contrato',
    'Contract manufacturing to a customer-owned design and specification — producing a defined product under controlled quality, with full traceability and PPAP-level documentation.',
    'Manufactura por contrato conforme a un diseño y especificación propiedad del cliente — produciendo un producto definido bajo calidad controlada, con trazabilidad completa y documentación nivel PPAP.',
    'execution',
    'OEM contract manufacturing is the production of a customer-designed product under defined commercial and quality terms. The customer owns the design — drawings, BOM, specifications, revisions — and we are responsible for executing production to that baseline with controlled quality, predictable lead time, and complete traceability. We treat OEM production as a program, not a transaction: a control plan governs every CTQ, an FAI is executed at process launch, PPAP documentation is maintained at the agreed level, and engineering changes flow through a documented change-control process before they reach the line. Our role spans supplier management (where the OEM product includes sub-tier components), production scheduling, in-process and final inspection, packaging specification, and shipment release. The objective is consistent, repeatable delivery of a product that conforms to the customer\'s technical baseline, batch after batch.',
    'La manufactura OEM por contrato es la producción de un producto diseñado por el cliente bajo términos comerciales y de calidad definidos. El cliente es dueño del diseño — planos, BOM, especificaciones, revisiones — y nosotros somos responsables de ejecutar la producción a esa línea base con calidad controlada, plazo predecible y trazabilidad completa. Tratamos la producción OEM como un programa, no como una transacción: un plan de control gobierna cada CTQ, se ejecuta un FAI al lanzamiento del proceso, la documentación PPAP se mantiene al nivel acordado, y los cambios de ingeniería fluyen por un proceso de control de cambios documentado antes de llegar a la línea. Nuestro rol abarca gestión de proveedores (cuando el producto OEM incluye componentes sub-tier), programación de producción, inspección en proceso y final, especificación de embalaje y liberación de envío. El objetivo es entrega consistente y repetible de un producto que cumpla la línea base técnica del cliente, lote tras lote.',
    'When you own the design and need controlled production capacity — established products requiring a qualified second source, products moving to Asia manufacturing for cost or capacity reasons, or production programs where the buyer needs technical oversight without operating the factory. Also applicable when ramping volume on a mature product where consistency is more important than design iteration.',
    'Cuando usted es dueño del diseño y necesita capacidad de producción controlada — productos establecidos que requieren una segunda fuente calificada, productos que se mueven a manufactura asiática por razones de costo o capacidad, o programas de producción donde el comprador necesita supervisión técnica sin operar la fábrica. También aplica cuando se escala el volumen de un producto maduro donde la consistencia es más importante que la iteración de diseño.',
    'Production begins with a production readiness review (PRR) confirming that drawings, BOM, tooling, control plan, and inspection plan are all current and aligned. The first production run is treated as a PPAP submission — first-article inspection, capacity study (Cpk/Ppk on CTQs), and full documentation package. Series production runs against the released control plan with in-process inspection at defined frequencies, material traceability maintained through lot identification, and final inspection before shipment release. A documented change-control process governs any engineering change — no change is implemented without buyer approval. Production status, quality data, and shipment readiness are reported on the cadence agreed with the buyer.',
    'La producción comienza con una Revisión de Preparación de Producción (PRR) confirmando que planos, BOM, herramentales, plan de control y plan de inspección están todos vigentes y alineados. La primera corrida de producción se trata como una presentación PPAP — inspección de primer artículo, estudio de capacidad (Cpk/Ppk en CTQs) y paquete documental completo. La producción en serie corre contra el plan de control liberado con inspección en proceso en frecuencias definidas, trazabilidad de material mantenida a través de identificación de lote, e inspección final antes de la liberación de envío. Un proceso de control de cambios documentado gobierna cualquier cambio de ingeniería — ningún cambio se implementa sin aprobación del comprador. El estado de producción, los datos de calidad y la preparación de envío se reportan en la cadencia acordada con el comprador.',
    [
      'Production readiness review (PRR) report',
      'Control plan, inspection plan, and material traceability procedure',
      'PPAP submission at agreed level (Level 3 typical for OEM)',
      'First-article inspection (FAI) report per AS9102-compatible format',
      'Production batch records with lot identification',
      'Final inspection and shipment release documentation',
    ],
    [
      'Informe de Revisión de Preparación de Producción (PRR)',
      'Plan de control, plan de inspección y procedimiento de trazabilidad de material',
      'Presentación PPAP al nivel acordado (Nivel 3 típico para OEM)',
      'Informe de inspección de primer artículo (FAI) en formato compatible con AS9102',
      'Registros de lote de producción con identificación de lote',
      'Documentación de inspección final y liberación de envío',
    ],
  ),
  service(
    'odm',
    'odm',
    'odm',
    'ODM Platform Development',
    'Desarrollo de Plataforma ODM',
    'Adaptable product development using proven technical platforms and manufacturing knowledge — reducing time-to-market and NRE exposure while preserving brand-specific differentiation.',
    'Desarrollo adaptable de productos usando plataformas técnicas probadas y conocimiento de manufactura — reduciendo tiempo al mercado y exposición NRE preservando la diferenciación específica de marca.',
    'engineering',
    'Original Design Manufacturing (ODM) is the development of a product on an existing, proven technical platform — adapting it to the customer\'s brand, market, and functional requirements without starting from a blank sheet. The customer gains time-to-market and avoids the full non-recurring engineering (NRE) cost of a from-scratch development; the trade-off is a degree of design constraint imposed by the platform. We manage that trade-off explicitly: we identify candidate platforms whose process route, material set, and manufacturing footprint match the program requirements, then scope the adaptation work — cosmetic customization, interface modification, functional extensions, regulatory certification — and execute the adaptation under APQP discipline. The result is a product that carries the customer\'s brand identity but leverages a manufacturing platform whose process capability, tooling, and quality system are already proven.',
    'La manufactura por diseño original (ODM) es el desarrollo de un producto sobre una plataforma técnica existente y probada — adaptándola a la marca, mercado y requisitos funcionales del cliente sin comenzar desde una hoja en blanco. El cliente gana tiempo al mercado y evita el costo total de ingeniería no recurrente (NRE) de un desarrollo desde cero; la contrapartida es un grado de restricción de diseño impuesto por la plataforma. Gestionamos esa compensación explícitamente: identificamos plataformas candidatas cuya ruta de proceso, conjunto de materiales y huella de manufactura coinciden con los requisitos del programa, luego delimitamos el trabajo de adaptación — personalización estética, modificación de interfaz, extensiones funcionales, certificación regulatoria — y ejecutamos la adaptación bajo disciplina APQP. El resultado es un producto que lleva la identidad de marca del cliente pero aprovecha una plataforma de manufactura cuya capacidad de proceso, herramentales y sistema de calidad ya están probados.',
    'When a market need can be met by adapting an existing technical platform rather than developing from scratch — cost-sensitive product launches, time-compressed market entries, brand extensions, or programs where the buyer wants to test market response before committing to a fully custom NRE investment. Particularly valuable when the buyer lacks a resident industrial design or manufacturing engineering team.',
    'Cuando una necesidad de mercado puede atenderse adaptando una plataforma técnica existente en lugar de desarrollar desde cero — lanzamientos de productos sensibles al costo, entradas a mercado comprimidas en tiempo, extensiones de marca, o programas donde el comprador quiere probar la respuesta del mercado antes de comprometerse a una inversión NRE totalmente personalizada. Particularmente valioso cuando el comprador carece de un equipo residente de diseño industrial o ingeniería de manufactura.',
    'We begin with a market and product brief from the customer, then screen candidate platforms against functional, regulatory, and commercial criteria. The selected platform is documented as a baseline — current drawings, BOM, process route, existing certifications, known constraints. We then define the adaptation scope: cosmetic changes (housing, branding, colorway), interface changes (connectors, controls, displays), functional extensions (additional sensors, communications, software features), and any re-certification work required. The adapted design is released under DFM/DFA review with the manufacturing partner, validated through the agreed APQP phases, and qualified through FAI and PPAP before series production. Tooling changes are limited to those strictly required by the adaptation — protecting the cost and schedule advantage of the platform approach.',
    'Comenzamos con un brief de mercado y producto del cliente, luego filtramos plataformas candidatas contra criterios funcionales, regulatorios y comerciales. La plataforma seleccionada se documenta como línea base — planos actuales, BOM, ruta de proceso, certificaciones existentes, restricciones conocidas. Luego definimos el alcance de adaptación: cambios estéticos (carcasa, marca, colorway), cambios de interfaz (conectores, controles, pantallas), extensiones funcionales (sensores adicionales, comunicaciones, características de software) y cualquier trabajo de recertificación requerido. El diseño adaptado se libera bajo revisión DFM/DFA con el socio de manufactura, se valida a través de las fases APQP acordadas y se califica mediante FAI y PPAP antes de la producción en serie. Los cambios de herramentales se limitan a los estrictamente requeridos por la adaptación — protegiendo la ventaja de costo y plazo del enfoque de plataforma.',
    [
      'Platform screening and selection report',
      'Adaptation scope document with functional and cosmetic deltas',
      'DFM/DFA review of the adapted design',
      'Updated drawings, BOM, and specifications',
      'Validation plan and APQP phase-gate record',
      'Re-certification package where applicable',
    ],
    [
      'Informe de filtrado y selección de plataforma',
      'Documento de alcance de adaptación con deltas funcionales y estéticos',
      'Revisión DFM/DFA del diseño adaptado',
      'Planos, BOM y especificaciones actualizados',
      'Plan de validación y registro de puertas de fase APQP',
      'Paquete de recertificación cuando aplica',
    ],
  ),
  service(
    'reverse-engineering',
    'reverse-engineering',
    'ingenieria-inversa',
    'Reverse Engineering & Legacy Reconstruction',
    'Ingeniería Inversa y Reconstrucción Heredada',
    'Technical reconstruction of legacy or unavailable components — converting worn physical samples, partial drawings, and tribal knowledge into a controlled, manufacturable engineering package.',
    'Reconstrucción técnica de componentes heredados o no disponibles — convirtiendo muestras físicas desgastadas, planos parciales y conocimiento tácito en un paquete de ingeniería controlado y fabricable.',
    'engineering',
    'Reverse engineering is the technical reconstruction of a component or assembly when complete original documentation is unavailable — typically because the original manufacturer has exited the market, the drawings were never transferred, or the part is being moved from an obsolete supply source. We treat reverse engineering as a structured engineering activity, not a measurement exercise. The work begins with capturing the geometry of available samples (3D scanning, CMM measurement, manual measurement), then cross-referencing that data against any available partial documentation, operating-environment knowledge, and wear patterns to reconstruct a complete engineering package: drawings with tolerances derived from functional intent, material specification based on operating conditions and failure analysis, surface finish and treatment specifications, and inspection plan. Where the original part\'s performance can be improved (wear life, corrosion resistance, weight), we present the option to the buyer with a documented trade-off.',
    'La ingeniería inversa es la reconstrucción técnica de un componente o conjunto cuando no se dispone de la documentación original completa — típicamente porque el fabricante original ha salido del mercado, los planos nunca se transfirieron, o la pieza se está moviendo de una fuente de suministro obsoleta. Tratamos la ingeniería inversa como una actividad de ingeniería estructurada, no como un ejercicio de medición. El trabajo comienza capturando la geometría de las muestras disponibles (escaneo 3D, medición CMM, medición manual), luego contrastando esos datos contra cualquier documentación parcial disponible, conocimiento del entorno operativo y patrones de desgaste para reconstruir un paquete de ingeniería completo: planos con tolerancias derivadas de la intención funcional, especificación de material basada en condiciones operativas y análisis de falla, especificaciones de acabado superficial y tratamiento, y plan de inspección. Cuando el desempeño de la pieza original puede mejorarse (vida útil al desgaste, resistencia a corrosión, peso), presentamos la opción al comprador con una compensación documentada.',
    'When a replacement part lacks complete drawings, technical data, or available spare supply — obsolescence scenarios, equipment with no OEM support, supply security programs, or any situation where the original technical baseline cannot be recovered from documentation alone. Particularly common in mining, energy, and heavy industrial equipment with long service lives.',
    'Cuando una pieza de reemplazo carece de planos completos, datos técnicos o repuestos disponibles — escenarios de obsolescencia, equipos sin soporte OEM, programas de seguridad de suministro, o cualquier situación donde la línea base técnica original no pueda recuperarse solo de la documentación. Particularmente común en equipos mineros, energéticos e industriales pesados con largas vidas de servicio.',
    'We begin by securing the best available physical samples — preferably new-old-stock, but worn samples are acceptable with appropriate interpretation. Geometry capture uses 3D scanning for complex surfaces and CMM for critical dimensions, supplemented by manual measurement of features difficult to scan. The captured data is cross-referenced with any available documentation (partial drawings, photos, operating manuals) and with the functional context provided by the buyer. We then construct a CAD model and 2D drawing with tolerances derived from functional intent (not from the worn sample), specify material based on the operating environment, and define a test plan to validate the reconstruction. A prototype is built and validated against samples before the engineering package is released for production.',
    'Comenzamos asegurando las mejores muestras físicas disponibles — preferiblemente inventario nuevo antiguo, pero muestras desgastadas son aceptables con interpretación apropiada. La captura de geometría usa escaneo 3D para superficies complejas y CMM para dimensiones críticas, complementado con medición manual de características difíciles de escanear. Los datos capturados se contrastan con cualquier documentación disponible (planos parciales, fotos, manuales de operación) y con el contexto funcional provisto por el comprador. Luego construimos un modelo CAD y plano 2D con tolerancias derivadas de la intención funcional (no de la muestra desgastada), especificamos el material según el entorno operativo y definimos un plan de prueba para validar la reconstrucción. Se construye un prototipo y se valida contra muestras antes de liberar el paquete de ingeniería para producción.',
    [
      'Geometry capture report (3D scan + CMM data)',
      'Reconstructed CAD model and 2D drawings with tolerances',
      'Material specification with operating-environment rationale',
      'Surface finish and treatment specification',
      'Inspection and validation plan',
      'Prototype validation report against reference samples',
    ],
    [
      'Informe de captura de geometría (escaneo 3D + datos CMM)',
      'Modelo CAD reconstruido y planos 2D con tolerancias',
      'Especificación de material con justificación de entorno operativo',
      'Especificación de acabado superficial y tratamiento',
      'Plan de inspección y validación',
      'Informe de validación de prototipo contra muestras de referencia',
    ],
  ),
  service(
    'tooling',
    'tooling',
    'herramentales',
    'Tooling Design & Build Coordination',
    'Coordinación de Diseño y Construcción de Herramentales',
    'Design coordination and controlled build of production tooling — injection molds, stamping dies, fixtures, gauges, and assembly tooling — with trial, qualification, and acceptance.',
    'Coordinación de diseño y construcción controlada de herramentales de producción — moldes de inyección, troqueles de estampado, dispositivos, calibres y herramentales de ensamblaje — con prueba, calificación y aceptación.',
    'engineering',
    'Tooling is the physical foundation of repeatable production. A well-designed and well-built tool delivers consistent parts at the required cycle time for the life of the program; a poorly designed tool delivers chronic quality problems, capacity loss, and unexpected cost. We coordinate the design, build, trial, and acceptance of production tooling across injection molds (single- and multi-cavity, hot- and cold-runner, overmolding and insert molding), stamping dies (progressive and transfer), fixtures (assembly, inspection, and test), and gauges. The work begins with a tooling specification derived from the technical baseline — part geometry, material, expected volume, cycle time target, and maintenance plan — and ends with a tooling acceptance record based on trial parts, dimensional verification, and process capability. Tooling ownership, maintenance responsibility, and storage are documented explicitly at the start to prevent ambiguity later in the program lifecycle.',
    'Los herramentales son la base física de la producción repetible. Un herramental bien diseñado y bien construido entrega piezas consistentes en el tiempo de ciclo requerido durante la vida del programa; un herramental mal diseñado entrega problemas crónicos de calidad, pérdida de capacidad y costos inesperados. Coordinamos el diseño, construcción, prueba y aceptación de herramentales de producción a través de moldes de inyección (una y múltiples cavidades, runner caliente y frío, sobremoldeo y moldeo con insertos), troqueles de estampado (progresivo y transferencia), dispositivos (ensamblaje, inspección y prueba) y calibres. El trabajo comienza con una especificación de herramental derivada de la línea base técnica — geometría de pieza, material, volumen esperado, objetivo de tiempo de ciclo y plan de mantenimiento — y termina con un registro de aceptación de herramental basado en piezas de prueba, verificación dimensional y capacidad de proceso. La propiedad de herramentales, la responsabilidad de mantenimiento y el almacenamiento se documentan explícitamente al inicio para prevenir ambigüedad más adelante en el ciclo de vida del programa.',
    'When repeatable production depends on a dedicated mold, die, jig, fixture, or gauge — new tooling for NPI programs, replacement tooling for transfer or worn-out situations, or capacity expansion through additional cavities/dies. Also applicable when existing tooling is underperforming (cycle time, dimensional stability, maintenance frequency) and a redesign is being evaluated.',
    'Cuando la producción repetible depende de un molde, troquel, plantilla, dispositivo o calibre dedicado — herramentales nuevos para programas NPI, herramentales de reemplazo para transferencia o desgaste, o expansión de capacidad a través de cavidades/troqueles adicionales. También aplica cuando los herramentales existentes tienen bajo desempeño (tiempo de ciclo, estabilidad dimensional, frecuencia de mantenimiento) y se evalúa un rediseño.',
    'We start with a tooling specification that defines part geometry, material, expected volume, cycle time target, tool life, maintenance plan, and ownership terms. The tool design is reviewed against DFM principles (draft angles, wall thickness, gating, ejection, cooling) and against the supplier\'s available equipment and capabilities. T1 sampling is the first opportunity to verify the tool\'s work — dimensional, cosmetic, and process parameters are documented and compared to specification. Iterations (T2, T3...) follow until the tool produces parts that meet specification at the target cycle time. Final acceptance is recorded with a tooling acceptance report, dimensional report on sampled parts, and a tool maintenance plan. Where required, we coordinate tooling ownership transfer terms in writing — protecting the buyer\'s ability to move production if needed.',
    'Comenzamos con una especificación de herramental que define geometría de pieza, material, volumen esperado, objetivo de tiempo de ciclo, vida del herramental, plan de mantenimiento y términos de propiedad. El diseño del herramental se revisa contra principios DFM (ángulos de desmoldeo, espesor de pared, alimentación, expulsión, enfriamiento) y contra el equipo y capacidades disponibles del proveedor. El muestreo T1 es la primera oportunidad de verificar el trabajo del herramental — dimensionales, estéticos y parámetros de proceso se documentan y comparan contra especificación. Siguen iteraciones (T2, T3...) hasta que el herramental produzca piezas que cumplan especificación al tiempo de ciclo objetivo. La aceptación final se registra con un informe de aceptación de herramental, informe dimensional de piezas muestreadas y un plan de mantenimiento del herramental. Cuando se requiere, coordinamos los términos de transferencia de propiedad de herramentales por escrito — protegiendo la capacidad del comprador de mover producción si se necesita.',
    [
      'Tooling specification document with ownership terms',
      'DFM review of tool design (draft, gating, ejection, cooling)',
      'T1/T2/T3 sampling reports with dimensional verification',
      'Tooling acceptance report and process capability data',
      'Tool maintenance plan and spare parts list',
      'Documented tooling ownership and transfer terms',
    ],
    [
      'Documento de especificación de herramental con términos de propiedad',
      'Revisión DFM del diseño del herramental (desmoldeo, alimentación, expulsión, enfriamiento)',
      'Informes de muestreo T1/T2/T3 con verificación dimensional',
      'Informe de aceptación de herramental y datos de capacidad de proceso',
      'Plan de mantenimiento del herramental y lista de refacciones',
      'Términos de propiedad y transferencia de herramentales documentados',
    ],
  ),
  service(
    'manufacturing-transfer',
    'manufacturing-transfer',
    'transferencia-de-manufactura',
    'Manufacturing Transfer',
    'Transferencia de Manufactura',
    'Orderly migration of production between sites, suppliers, or regions — preserving process knowledge, quality controls, and dimensional continuity across the transition.',
    'Migración ordenada de producción entre plantas, proveedores o regiones — preservando conocimiento de proceso, controles de calidad y continuidad dimensional a lo largo de la transición.',
    'execution',
    'Manufacturing transfer is the controlled relocation of a production program from one site, supplier, or region to another — without losing process knowledge, quality control continuity, or dimensional stability. Transfers fail when they are treated as a logistics exercise; they succeed when they are managed as a controlled engineering program. We structure transfers in four phases: baseline capture (current part data, process parameters, control plan, quality history), receiving site qualification (capability verification against the baseline), parallel production (overlap between old and new source for verification and continuity), and source switch (final transfer with old source retired on schedule). The technical baseline — drawings, BOM, control plan, tooling — is the contract between the two sites; any deviation is documented and resolved before the new source ships parts to the buyer.',
    'La transferencia de manufactura es la reubicación controlada de un programa de producción de un sitio, proveedor o región a otro — sin perder conocimiento de proceso, continuidad de control de calidad o estabilidad dimensional. Las transferencias fallan cuando se tratan como un ejercicio logístico; tienen éxito cuando se gestionan como un programa de ingeniería controlado. Estructuramos las transferencias en cuatro fases: captura de línea base (datos actuales de pieza, parámetros de proceso, plan de control, historial de calidad), calificación del sitio receptor (verificación de capacidad contra la línea base), producción paralela (superposición entre fuente vieja y nueva para verificación y continuidad), y conmutación de fuente (transferencia final con la fuente vieja retirada según cronograma). La línea base técnica — planos, BOM, plan de control, herramentales — es el contrato entre los dos sitios; cualquier desviación se documenta y resuelve antes de que la nueva fuente envíe piezas al comprador.',
    'When a product must move without losing process knowledge or quality controls — supplier consolidation, supplier exit, capacity reallocation, geopolitical risk mitigation, nearshoring, or cost-driven relocation. Critical when the product has long-running quality history at the old source and any dimensional or cosmetic discontinuity would be visible to the end customer.',
    'Cuando un producto debe trasladarse sin perder conocimiento de proceso ni controles de calidad — consolidación de proveedores, salida de proveedor, reasignación de capacidad, mitigación de riesgo geopolítico, nearshoring o reubicación por costo. Crítico cuando el producto tiene un largo historial de calidad en la fuente vieja y cualquier discontinuidad dimensional o estética sería visible para el cliente final.',
    'We begin by capturing the baseline at the originating source: dimensional data on a representative sample (typically 30–50 parts across the existing production range), in-process parameter settings, control plan, known quality issues, and tooling status. The receiving site is then qualified against this baseline — FAI on first parts, dimensional overlay against the originating source data, and process capability verification. Parallel production runs for an agreed period, with both sources shipping to the buyer and dimensional data compared batch-by-batch. Once dimensional continuity and quality parity are confirmed, the originating source is retired on schedule, and the receiving site becomes the sole production source. The transfer record — baseline data, qualification evidence, parallel production data — is archived as the new source\'s starting baseline.',
    'Comenzamos capturando la línea base en la fuente de origen: datos dimensionales en una muestra representativa (típicamente 30–50 piezas a lo largo del rango de producción existente), parámetros de proceso en uso, plan de control, problemas de calidad conocidos y estado de herramentales. El sitio receptor se califica luego contra esta línea base — FAI en primeras piezas, superposición dimensional contra los datos de la fuente de origen y verificación de capacidad de proceso. La producción paralela corre por un período acordado, con ambas fuentes enviando al comprador y datos dimensionales comparados lote por lote. Una vez confirmada la continuidad dimensional y la paridad de calidad, la fuente de origen se retira según cronograma, y el sitio receptor se convierte en la única fuente de producción. El registro de transferencia — datos de línea base, evidencia de calificación, datos de producción paralela — se archiva como la línea base inicial de la nueva fuente.',
    [
      'Baseline dimensional data from originating source',
      'Receiving site qualification report (FAI + capability study)',
      'Parallel production plan with batch-level data comparison',
      'Dimensional continuity verification across both sources',
      'Tooling transfer record (where applicable)',
      'Source switch authorization and final transfer record',
    ],
    [
      'Datos dimensionales de línea base de la fuente de origen',
      'Informe de calificación del sitio receptor (FAI + estudio de capacidad)',
      'Plan de producción paralela con comparación de datos a nivel lote',
      'Verificación de continuidad dimensional entre ambas fuentes',
      'Registro de transferencia de herramentales (cuando aplica)',
      'Autorización de conmutación de fuente y registro final de transferencia',
    ],
  ),
  service(
    'factory-audits',
    'factory-audits',
    'auditorias-de-fabrica',
    'Factory Audits',
    'Auditorías de Fábrica',
    'On-site or hybrid assessment of manufacturing systems, process capability, and project readiness — providing documented evidence of supplier capability before commitment.',
    'Evaluación in situ o híbrida de sistemas de manufactura, capacidad de proceso y preparación de proyecto — proporcionando evidencia documentada de la capacidad del proveedor antes del compromiso.',
    'quality',
    'Factory audits provide an independent, documented assessment of a manufacturer\'s capability against the requirements of a specific program. We do not perform generic ISO-style audits; we audit against the program\'s requirements — process route, tolerance class, regulatory regime, documentation expectations, capacity profile. The audit covers four areas in depth: manufacturing capability (equipment list, age, condition, capability studies on relevant processes), quality system (control plans, MSA, calibration, traceability, nonconformance management, corrective action effectiveness), program execution (project management, change control, escalation paths, communication discipline), and operational maturity (workforce stability, financial indicators, business continuity). Findings are categorized by severity and probability, with corrective actions tracked to closure. The audit report is the evidence base for go/no-go sourcing decisions and for the qualification plan that follows.',
    'Las auditorías de fábrica proporcionan una evaluación independiente y documentada de la capacidad de un fabricante frente a los requisitos de un programa específico. No realizamos auditorías genéricas estilo ISO; auditamos contra los requisitos del programa — ruta de proceso, clase de tolerancia, régimen regulatorio, expectativas de documentación, perfil de capacidad. La auditoría cubre cuatro áreas en profundidad: capacidad de manufactura (lista de equipo, edad, condición, estudios de capacidad en procesos relevantes), sistema de calidad (planes de control, MSA, calibración, trazabilidad, gestión de no conformidades, efectividad de acción correctiva), ejecución de programa (gestión de proyectos, control de cambios, rutas de escalamiento, disciplina de comunicación) y madurez operativa (estabilidad de personal, indicadores financieros, continuidad de negocio). Los hallazgos se categorizan por severidad y probabilidad, con acciones correctivas rastreadas hasta su cierre. El informe de auditoría es la base de evidencia para decisiones de abastecimiento sí/no y para el plan de calificación que sigue.',
    'When you need evidence of process capability, controls, and operational maturity — first-time supplier engagement, significant volume increase, change of supplier ownership, recurring quality issues, or pre-acquisition due diligence. Also valuable as periodic re-verification of critical suppliers.',
    'Cuando necesita evidencia de capacidad de proceso, controles y madurez operativa — contratación de proveedor por primera vez, aumento significativo de volumen, cambio de propiedad del proveedor, problemas de calidad recurrentes o debida diligencia pre-adquisición. También valioso como reverificación periódica de proveedores críticos.',
    'Audits are scoped against the program requirements — we develop an audit plan that defines the areas to be assessed, the questions to be answered, the evidence to be collected, and the criteria for acceptability. The on-site audit typically runs 1–2 days and includes facility tour, equipment inspection, document review (control plans, MSA, calibration records, nonconformance logs, corrective action history), interviews with quality and production leadership, and direct observation of relevant processes. Findings are documented with photographic evidence, categorized by severity, and reviewed with the supplier at a closing meeting. A formal audit report is issued within an agreed timeframe; corrective actions, where required, are tracked to closure with verification of effectiveness. The audit can be combined with first-article inspection or process capability study for additional evidence.',
    'Las auditorías se delimitan contra los requisitos del programa — desarrollamos un plan de auditoría que define las áreas a evaluar, las preguntas a responder, la evidencia a recolectar y los criterios de aceptabilidad. La auditoría in situ típicamente dura 1–2 días e incluye recorrido de instalación, inspección de equipo, revisión documental (planes de control, MSA, registros de calibración, bitácoras de no conformidad, historial de acciones correctivas), entrevistas con liderazgo de calidad y producción, y observación directa de procesos relevantes. Los hallazgos se documentan con evidencia fotográfica, se categorizan por severidad y se revisan con el proveedor en una reunión de cierre. Se emite un informe formal de auditoría dentro de un plazo acordado; las acciones correctivas, cuando se requieren, se rastrean hasta su cierre con verificación de efectividad. La auditoría puede combinarse con inspección de primer artículo o estudio de capacidad de proceso para evidencia adicional.',
    [
      'Audit plan scoped to program requirements',
      'Documented findings with photographic evidence',
      'Findings report categorized by severity',
      'Corrective action plan with owners and due dates',
      'Verification of corrective action effectiveness',
      'Go/no-go sourcing recommendation',
    ],
    [
      'Plan de auditoría delimitado a los requisitos del programa',
      'Hallazgos documentados con evidencia fotográfica',
      'Informe de hallazgos categorizado por severidad',
      'Plan de acción correctiva con responsables y fechas',
      'Verificación de efectividad de acciones correctivas',
      'Recomendación de abastecimiento sí/no',
    ],
  ),
  service(
    'supply-chain-development',
    'supply-chain-development',
    'desarrollo-de-cadena-de-suministro',
    'Supply Chain Development',
    'Desarrollo de Cadena de Suministro',
    'Development of a resilient, qualified manufacturing ecosystem for a product family — mapping dependencies, qualifying alternatives, and defining the conditions under which the chain can flex without quality disruption.',
    'Desarrollo de un ecosistema de manufactura resiliente y calificado para una familia de productos — mapeando dependencias, calificando alternativas y definiendo las condiciones bajo las cuales la cadena puede flexionar sin disrupción de calidad.',
    'supply-chain',
    'Supply chain development is the engineering of a manufacturing ecosystem that can absorb disruption without losing quality continuity. A resilient supply chain is not built by adding suppliers — it is built by understanding dependencies, qualifying alternatives before they are needed, and defining the conditions under which the chain can flex. We map the supply chain for a product family — every process, every supplier, every long-lead material, every single point of failure — and we qualify alternatives in advance so that switching is a controlled engineering event, not an emergency. The work covers supplier qualification (per the qualification methodology above), second-source planning, inventory positioning (raw material, work-in-progress, finished goods), and the documentation regime (drawings, specifications, control plans) that allows a new supplier to be brought online without re-engineering. The output is a supply chain that has resilience designed in, not bolted on after a disruption.',
    'El desarrollo de la cadena de suministro es la ingeniería de un ecosistema de manufactura que pueda absorber disrupción sin perder continuidad de calidad. Una cadena de suministro resiliente no se construye agregando proveedores — se construye entendiendo dependencias, calificando alternativas antes de necesitarlas, y definiendo las condiciones bajo las cuales la cadena puede flexionar. Mapeamos la cadena de suministro de una familia de productos — cada proceso, cada proveedor, cada material de largo plazo, cada punto único de falla — y calificamos alternativas por adelantado para que la conmutación sea un evento de ingeniería controlado, no una emergencia. El trabajo cubre calificación de proveedores (según la metodología de calificación anterior), planificación de segunda fuente, posicionamiento de inventario (material en bruto, trabajo en progreso, producto terminado) y el régimen documental (planos, especificaciones, planes de control) que permite a un nuevo proveedor entrar en operación sin reingeniería. La salida es una cadena de suministro con resiliencia diseñada, no atornillada después de una disrupción.',
    'When supply continuity depends on more than one process, supplier, or region — multi-component assemblies, regulated supply chains, geopolitical risk exposure, or any product family where a single disruption would stop the buyer\'s line. Particularly valuable for long-running programs where the cost of disruption dwarfs the cost of preparedness.',
    'Cuando la continuidad de suministro depende de más de un proceso, proveedor o región — conjuntos multicomponente, cadenas reguladas, exposición a riesgo geopolítico, o cualquier familia de productos donde una sola disrupción detendría la línea del comprador. Particularmente valioso para programas de larga duración donde el costo de disrupción enana el costo de preparación.',
    'We start with a supply chain map for the product family: every component, every supplier, every process, every long-lead material, every interface. Single points of failure are flagged; resilience gaps are quantified. For each gap, we define a mitigation strategy — second-source qualification, strategic inventory, design alternative, or accepted risk with monitoring. Where second sources are required, we execute the qualification methodology in advance so the alternative is ready when needed. The documentation regime — controlled drawings, BOMs, control plans — is maintained current so a new source can be brought online without re-engineering. A periodic resilience review (typically quarterly) verifies that the chain\'s assumptions still hold and that mitigation actions are progressing.',
    'Comenzamos con un mapa de cadena de suministro para la familia de productos: cada componente, cada proveedor, cada proceso, cada material de largo plazo, cada interfaz. Los puntos únicos de falla se marcan; las brechas de resiliencia se cuantifican. Para cada brecha, definimos una estrategia de mitigación — calificación de segunda fuente, inventario estratégico, alternativa de diseño, o riesgo aceptado con monitoreo. Cuando se requieren segundas fuentes, ejecutamos la metodología de calificación por adelantado para que la alternativa esté lista cuando se necesite. El régimen documental — planos controlados, BOMs, planes de control — se mantiene vigente para que una nueva fuente pueda entrar en operación sin reingeniería. Una revisión periódica de resiliencia (típicamente trimestral) verifica que los supuestos de la cadena sigan vigentes y que las acciones de mitigación estén progresando.',
    [
      'Supply chain map with dependencies and single points of failure',
      'Resilience gap assessment with quantified risk',
      'Second-source qualification plan and execution',
      'Strategic inventory positioning recommendation',
      'Controlled documentation regime (drawings, BOMs, control plans)',
      'Periodic resilience review schedule',
    ],
    [
      'Mapa de cadena de suministro con dependencias y puntos únicos de falla',
      'Evaluación de brechas de resiliencia con riesgo cuantificado',
      'Plan de calificación de segunda fuente y su ejecución',
      'Recomendación de posicionamiento de inventario estratégico',
      'Régimen de documentación controlada (planos, BOMs, planes de control)',
      'Cronograma de revisión periódica de resiliencia',
    ],
  ),
  service(
    'strategic-sourcing',
    'strategic-sourcing',
    'sourcing-estrategico',
    'Strategic Sourcing',
    'Sourcing Estratégico',
    'Technically informed sourcing strategy for defined industrial requirements — comparing suppliers on total execution risk, not just unit price, and structuring the award for long-term value.',
    'Estrategia de abastecimiento técnicamente informada para requisitos industriales definidos — comparando proveedores en riesgo total de ejecución, no solo en precio unitario, y estructurando la adjudicación para valor de largo plazo.',
    'supply-chain',
    'Strategic sourcing at the industrial level is the structured selection of a manufacturing source based on total execution risk, not a price comparison. We treat sourcing as an engineering decision: the supplier\'s process capability, capacity profile, quality system maturity, geographic risk, financial stability, and program execution track record are evaluated alongside unit price, lead time, and commercial terms. The output is not a price table — it is a sourcing recommendation that documents the basis of award, the residual risks accepted, the performance metrics that will govern the relationship, and the conditions under which the buyer retains the right to re-source. This approach is particularly valuable for programs where unit-price differences are small relative to the cost of a quality escape, a delivery delay, or a supplier failure mid-program.',
    'El sourcing estratégico a nivel industrial es la selección estructurada de una fuente de manufactura basada en riesgo total de ejecución, no una comparación de precios. Tratamos el sourcing como una decisión de ingeniería: la capacidad de proceso del proveedor, el perfil de capacidad, la madurez del sistema de calidad, el riesgo geográfico, la estabilidad financiera y el historial de ejecución de programas se evalúan junto al precio unitario, plazo y términos comerciales. La salida no es una tabla de precios — es una recomendación de abastecimiento que documenta la base de adjudicación, los riesgos residuales aceptados, las métricas de desempeño que gobernarán la relación y las condiciones bajo las cuales el comprador retiene el derecho de re-abastecer. Este enfoque es particularmente valioso para programas donde las diferencias de precio unitario son pequeñas relativas al costo de una fuga de calidad, un retraso de entrega o una falla de proveedor a mitad de programa.',
    'When a category needs a technically informed sourcing strategy, not a simple price comparison — new product launches, supplier consolidation, capacity expansion, re-sourcing after quality issues, or strategic categories where the cost of supplier failure exceeds any unit-price advantage.',
    'Cuando una categoría necesita una estrategia de abastecimiento técnicamente informada, no una simple comparación de precios — lanzamientos de nuevos productos, consolidación de proveedores, expansión de capacidad, re-abastecimiento tras problemas de calidad, o categorías estratégicas donde el costo de falla del proveedor excede cualquier ventaja de precio unitario.',
    'Sourcing begins with a category strategy that defines the requirements — technical, quality, capacity, lead time, regulatory, commercial. We then identify a candidate pool (typically 3–5 suppliers) and execute a structured RFQ with a common technical baseline. Supplier responses are evaluated on a weighted scorecard covering technical capability, quality system maturity, capacity and lead time, commercial terms, and program execution risk. Where appropriate, we run factory audits and first-article inspections to validate supplier claims. The recommended source is documented in a sourcing recommendation with the basis of award, residual risks, performance metrics, and re-source triggers. Negotiation support is provided as needed; the final commercial terms remain between the buyer and the supplier.',
    'El abastecimiento comienza con una estrategia de categoría que define los requisitos — técnicos, de calidad, de capacidad, de plazo, regulatorios, comerciales. Luego identificamos un conjunto candidato (típicamente 3–5 proveedores) y ejecutamos un RFQ estructurado con una línea base técnica común. Las respuestas de los proveedores se evalúan en una tarjeta de puntuación ponderada que cubre capacidad técnica, madurez del sistema de calidad, capacidad y plazo, términos comerciales y riesgo de ejecución del programa. Cuando es apropiado, realizamos auditorías de fábrica e inspecciones de primer artículo para validar las afirmaciones del proveedor. La fuente recomendada se documenta en una recomendación de abastecimiento con la base de adjudicación, riesgos residuales, métricas de desempeño y disparadores de re-abastecimiento. Se proporciona soporte de negociación según se necesite; los términos comerciales finales permanecen entre el comprador y el proveedor.',
    [
      'Category strategy document with requirement definition',
      'Structured RFQ package with common technical baseline',
      'Weighted supplier scorecard with technical and commercial criteria',
      'Sourcing recommendation with basis of award',
      'Residual risk register and performance metrics',
      'Re-source trigger conditions documented',
    ],
    [
      'Documento de estrategia de categoría con definición de requisitos',
      'Paquete RFQ estructurado con línea base técnica común',
      'Tarjeta de puntuación de proveedor ponderada con criterios técnicos y comerciales',
      'Recomendación de abastecimiento con base de adjudicación',
      'Registro de riesgos residuales y métricas de desempeño',
      'Condiciones de disparador de re-abastecimiento documentadas',
    ],
  ),
  service(
    'nearshoring-support',
    'nearshoring-support',
    'soporte-de-nearshoring',
    'Nearshoring & Regional Manufacturing Transfer',
    'Nearshoring y Transferencia Regional de Manufactura',
    'Manufacturing setup, supplier qualification, and production transfer support for companies relocating operations between regions — particularly Asia to Latin America (Mexico and Central America).',
    'Configuración de manufactura, calificación de proveedores y soporte de transferencia de producción para empresas que relocalizan operaciones entre regiones — particularmente Asia a América Latina (México y Centroamérica).',
    'supply-chain',
    'Nearshoring is a regional manufacturing transfer — relocating production capability to a closer geography for tariff, logistics, lead-time, or geopolitical reasons. The decision is rarely about labor cost alone; it is about process capability, supplier ecosystem maturity, and the speed at which a new region can reach stable quality. We treat nearshoring as a controlled manufacturing transfer, not a green-field startup: the technical baseline is frozen at the originating source, qualified local and hybrid supply routes are identified, and inspection and ramp-up criteria are defined before volumes move. Our role spans the full transfer lifecycle — readiness assessment, supplier qualification in the receiving region, parallel production with the originating source, source switch with dimensional continuity verification, and post-transfer support during ramp-up. We connect China manufacturing knowledge with execution requirements in Mexico and Latin America, supporting both companies moving production out of China and Chinese manufacturers establishing Mexican operations.',
    'El nearshoring es una transferencia regional de manufactura — relocalizando capacidad de producción a una geografía más cercana por razones arancelarias, logísticas, de plazo o geopolíticas. La decisión rara vez se trata solo de costo laboral; se trata de capacidad de proceso, madurez del ecosistema de proveedores y la velocidad con la que una nueva región puede alcanzar calidad estable. Tratamos el nearshoring como una transferencia de manufactura controlada, no como un arranque green-field: la línea base técnica se congela en la fuente de origen, se identifican rutas de suministro locales e híbridas calificadas, y se definen criterios de inspección y ramp-up antes de mover volúmenes. Nuestro rol abarca el ciclo completo de transferencia — evaluación de preparación, calificación de proveedores en la región receptora, producción paralela con la fuente de origen, conmutación de fuente con verificación de continuidad dimensional y soporte post-transferencia durante el ramp-up. Conectamos el conocimiento de manufactura en China con los requisitos de ejecución en México y América Latina, apoyando tanto a empresas que mueven producción fuera de China como a fabricantes chinos estableciendo operaciones mexicanas.',
    'When a company is evaluating or executing a move of production capability between regions — Asia to Latin America (Mexico, Central America), Latin America to Asia, or any cross-region relocation where technical qualification, transfer control, and supplier readiness are required to maintain quality continuity.',
    'Cuando una empresa está evaluando o ejecutando el traslado de capacidad productiva entre regiones — Asia a América Latina (México, Centroamérica), América Latina a Asia, o cualquier reubicación interregional donde se requiera calificación técnica, control de transferencia y preparación de proveedores para mantener continuidad de calidad.',
    'We begin with a nearshoring readiness assessment — technical baseline maturity at the originating source, supplier ecosystem maturity in the receiving region, regulatory and tariff considerations, and the operational gaps that must be closed before transfer. We then execute a structured transfer plan: supplier qualification in the receiving region (per the qualification methodology), parallel production for verification, dimensional continuity checks against the originating source data, and a defined source switch with the originating source retired on schedule. Tooling transfer is coordinated with explicit ownership and acceptance terms. Ramp-up criteria — first-article inspection, capacity verification, quality data trending — are defined in advance; post-transfer support covers the early production period until stable quality is achieved. Throughout, we serve as the technical bridge between the originating source\'s process knowledge and the receiving region\'s execution.',
    'Comenzamos con una evaluación de preparación para nearshoring — madurez de la línea base técnica en la fuente de origen, madurez del ecosistema de proveedores en la región receptora, consideraciones regulatorias y arancelarias, y las brechas operativas que deben cerrarse antes de la transferencia. Luego ejecutamos un plan estructurado de transferencia: calificación de proveedores en la región receptora (según la metodología de calificación), producción paralela para verificación, verificaciones de continuidad dimensional contra los datos de la fuente de origen y una conmutación de fuente definida con la fuente de origen retirada según cronograma. La transferencia de herramentales se coordina con términos explícitos de propiedad y aceptación. Los criterios de ramp-up — inspección de primer artículo, verificación de capacidad, tendencia de datos de calidad — se definen por adelantado; el soporte post-transferencia cubre el período inicial de producción hasta alcanzar calidad estable. Durante todo el proceso, servimos como puente técnico entre el conocimiento de proceso de la fuente de origen y la ejecución de la región receptora.',
    [
      'Nearshoring readiness assessment report',
      'Supplier qualification plan for receiving region',
      'Technical baseline freeze and transfer documentation',
      'Parallel production plan with dimensional continuity verification',
      'Tooling transfer record with ownership and acceptance terms',
      'Ramp-up criteria and post-transfer support plan',
    ],
    [
      'Informe de evaluación de preparación para nearshoring',
      'Plan de calificación de proveedores para la región receptora',
      'Congelación de línea base técnica y documentación de transferencia',
      'Plan de producción paralela con verificación de continuidad dimensional',
      'Registro de transferencia de herramentales con términos de propiedad y aceptación',
      'Criterios de ramp-up y plan de soporte post-transferencia',
    ],
  ),
];
