import type { Solution } from './types';

const l = (en: string, es: string) => ({ en, es });
const a = (en: string[], es: string[]) => ({ en, es });

export const solutions: Solution[] = [
  {
    id: 'plastic-injection',
    slug: l('plastic-injection', 'inyeccion-plastica'),
    title: l('Plastic Injection Molding', 'Inyección Plástica'),
    summary: l(
      'Engineered molded components from DFM review and mold-flow analysis through stable, validated production — single- and multi-cavity, hot- and cold-runner, overmolding and insert molding.',
      'Componentes moldeados de ingeniería desde revisión DFM y análisis de flujo de molde hasta producción estable y validada — una y múltiples cavidades, runner caliente y frío, sobremoldeo y moldeo con insertos.',
    ),
    problem: l(
      'Plastic injection molding is a system, not a process. Part geometry, resin selection, mold design, gating, cooling, ejection, and cosmetic requirements must work together; failure in any dimension shows up as dimensional instability, cosmetic defects, sink, warp, short shots, flash, or weld-line weakness. Tooling investment is significant and amortized across program volume — a poorly designed mold or a poorly matched resin choice drives chronic quality cost that exceeds any unit-price advantage. PPAP and capacity studies (Cpk on critical dimensions) are the gate to series production; without them, the program is exposed to drift that surfaces only after volumes ramp.',
      'La inyección plástica es un sistema, no un proceso. La geometría de pieza, selección de resina, diseño de molde, alimentación, enfriamiento, expulsión y requisitos estéticos deben funcionar en conjunto; la falla en cualquier dimensión aparece como inestabilidad dimensional, defectos estéticos, hundimiento, alabeo, llenado incompleto, rebarba o debilidad en línea de soldadura. La inversión en herramentales es significativa y se amortiza a lo largo del volumen del programa — un molde mal diseñado o una resina mal seleccionada genera costo crónico de calidad que excede cualquier ventaja de precio unitario. PPAP y estudios de capacidad (Cpk en dimensiones críticas) son la puerta a producción en serie; sin ellos, el programa se expone a deriva que aparece solo después de escalar el volumen.',
    ),
    approach: l(
      'We coordinate the full injection molding lifecycle: DFM review (draft, wall thickness, rib design, boss design, gating, ejection, cooling layout), mold-flow analysis to predict fill patterns, weld lines, and air traps, resin selection against the operating environment (mechanical, thermal, chemical, regulatory), tool build with T1/T2/T3 sampling iterations, dimensional verification against CTQs, and PPAP submission at the agreed level. Mold maintenance is planned from the start — preventive schedule, spare cavities, wear components — so that tooling uptime supports the program volume. Cosmetic-critical applications receive additional attention: A-grade surface definition, gating placement for aesthetic zones, and process parameters tuned for surface finish.',
      'Coordinamos el ciclo completo de inyección plástica: revisión DFM (desmoldeo, espesor de pared, diseño de nervaduras, diseño de boss, alimentación, expulsión, distribución de enfriamiento), análisis de flujo de molde para predecir patrones de llenado, líneas de soldadura y atrapes de aire, selección de resina contra el entorno operativo (mecánico, térmico, químico, regulatorio), construcción de molde con iteraciones de muestreo T1/T2/T3, verificación dimensional contra CTQs y presentación PPAP al nivel acordado. El mantenimiento del molde se planifica desde el inicio — cronograma preventivo, cavidades de respaldo, componentes de desgaste — para que el uptime del herramental soporte el volumen del programa. Las aplicaciones estéticamente críticas reciben atención adicional: definición de superficie grado A, ubicación de alimentación para zonas estéticas y parámetros de proceso ajustados para acabado superficial.',
    ),
    capabilities: a(
      [
        'DFM review and mold-flow analysis coordination',
        'Single- and multi-cavity tooling (up to 64+ cavities)',
        'Hot-runner and cold-runner systems',
        'Overmolding and insert molding',
        'Engineering resins: PC, PA, POM, PBT, PPS, PEEK, LCP, glass-filled',
        'Cosmetic-critical molding (A-grade surfaces, lens-quality)',
        'In-mold decoration and two-shot processing',
        'T1/T2/T3 sampling and qualification to PPAP',
      ],
      [
        'Coordinación de revisión DFM y análisis de flujo de molde',
        'Herramentales de una y múltiples cavidades (hasta 64+ cavidades)',
        'Sistemas de runner caliente y frío',
        'Sobremoldeo y moldeo con insertos',
        'Resinas de ingeniería: PC, PA, POM, PBT, PPS, PEEK, LCP, carga de fibra de vidrio',
        'Moldeo estéticamente crítico (superficies grado A, calidad óptica)',
        'Decoración en molde y procesamiento de dos componentes',
        'Muestreo T1/T2/T3 y calificación a PPAP',
      ],
    ),
    relatedIndustries: ['automotive', 'medical', 'consumer-goods', 'packaging', 'electronics'],
    relatedServices: ['engineering', 'tooling', 'quality-control', 'oem'],
  },
  {
    id: 'metal-manufacturing',
    slug: l('metal-manufacturing', 'manufactura-metalica'),
    title: l('Metal Manufacturing', 'Manufactura Metálica'),
    summary: l(
      'Machined, formed, cast, and fabricated metal components for industrial use — controlled process routes from drawing review through inspection, surface treatment, and packaging.',
      'Componentes metálicos mecanizados, conformados, fundidos y fabricados para uso industrial — rutas de proceso controladas desde la revisión de planos hasta inspección, tratamiento superficial y embalaje.',
    ),
    problem: l(
      'Metal manufacturing spans many processes — CNC milling, CNC turning, sheet metal forming (stamping, bending, deep drawing), welding (MIG, TIG, spot, laser), casting (sand, investment, die-casting), forging, and surface treatment (anodizing, plating, powder coating, e-coating). Each process has its own tolerance capability, defect modes, and inspection requirements. The challenge is selecting the right process route for the function and cost target, then controlling it consistently. Material certification, weld procedure qualification (WPS/PQR), heat treatment verification, and surface treatment thickness/adhesion are quality inputs that must be specified and verified — not assumed. Multi-process assemblies require interface control between processes to prevent accumulated tolerance stack-up.',
      'La manufactura metálica abarca muchos procesos — fresado CNC, torneado CNC, conformado de lámina metálica (estampado, doblado, embutido profundo), soldadura (MIG, TIG, punto, láser), fundición (arena, inversión, inyección), forjado y tratamiento superficial (anodizado, plateado, pintura en polvo, electrorecubrimiento). Cada proceso tiene su propia capacidad de tolerancia, modos de defecto y requisitos de inspección. El reto es seleccionar la ruta de proceso correcta para la función y costo objetivo, luego controlarla consistentemente. La certificación de material, la calificación de procedimiento de soldadura (WPS/PQR), la verificación de tratamiento térmico y el espesor/adherencia del tratamiento superficial son entradas de calidad que deben especificarse y verificarse — no asumirse. Los conjuntos multiproceso requieren control de interfaz entre procesos para prevenir el apilamiento acumulado de tolerancias.',
    ),
    approach: l(
      'We establish a controlled process route from drawing review to inspection and packaging. Material specification is verified against the operating environment — strength, corrosion resistance, temperature, fatigue life, conductivity. Tolerances are matched to process capability (CNC milling ±0.025mm typical, sheet metal ±0.1mm, casting ±0.5mm). Weld procedures are qualified to AWS / ISO 15614 standards as required; welders carry qualification records. Heat treatment is specified and verified through hardness testing or microstructure examination. Surface treatment is specified (coating thickness, adhesion, corrosion resistance per salt-spray test). Inspection covers dimensional, visual, and documentation verification — material certificates (3.1 / 3.2 per EN 10204), weld records, heat treatment charts, and treatment thickness readings are part of the release package.',
      'Establecemos una ruta de proceso controlada desde la revisión de planos hasta la inspección y el embalaje. La especificación de material se verifica contra el entorno operativo — resistencia, resistencia a corrosión, temperatura, vida a la fatiga, conductividad. Las tolerancias se ajustan a la capacidad del proceso (fresado CNC ±0,025 mm típico, lámina metálica ±0,1 mm, fundición ±0,5 mm). Los procedimientos de soldadura se califican según normas AWS / ISO 15614 según se requiera; los soldadores llevan registros de calificación. El tratamiento térmico se especifica y verifica a través de ensayos de dureza o examen de microestructura. El tratamiento superficial se especifica (espesor de recubrimiento, adherencia, resistencia a corrosión por ensayo de niebla salina). La inspección cubre verificación dimensional, visual y documental — los certificados de material (3.1 / 3.2 según EN 10204), registros de soldadura, gráficos de tratamiento térmico y lecturas de espesor de tratamiento son parte del paquete de liberación.',
    ),
    capabilities: a(
      [
        'CNC milling (3-, 4-, 5-axis)',
        'CNC turning with live tooling',
        'Sheet metal: stamping, bending, deep drawing, laser cutting',
        'Welding: MIG, TIG, spot, laser (WPS / PQR qualified)',
        'Casting: sand, investment (lost-wax), die-casting (HPDC)',
        'Forging: open-die and closed-die',
        'Heat treatment: quench, temper, anneal, age-harden',
        'Surface treatment: anodize, plate, powder coat, e-coat, passivate',
      ],
      [
        'Fresado CNC (3, 4, 5 ejes)',
        'Torneado CNC con herramienta viva',
        'Lámina metálica: estampado, doblado, embutido profundo, corte láser',
        'Soldadura: MIG, TIG, punto, láser (WPS / PQR calificadas)',
        'Fundición: arena, inversión (cera perdida), inyección (HPDC)',
        'Forjado: matriz abierta y cerrada',
        'Tratamiento térmico: temple, revenido, recocido, envejecimiento',
        'Tratamiento superficial: anodizado, plateado, pintura en polvo, electrorecubrimiento, pasivado',
      ],
    ),
    relatedIndustries: ['automotive', 'industrial-equipment', 'energy', 'mining', 'construction'],
    relatedServices: ['engineering', 'quality-control', 'manufacturing-supervision'],
  },
  {
    id: 'industrial-equipment',
    slug: l('industrial-equipment', 'equipos-industriales'),
    title: l('Industrial Equipment & Skid Packages', 'Equipos Industriales y Paquetes Skid'),
    summary: l(
      'Custom equipment, process skids, and integrated assemblies built around operating requirements — with managed interfaces, complete documentation, and field-ready verification.',
      'Equipos a medida, skids de proceso y conjuntos integrados construidos según requisitos operativos — con interfaces gestionadas, documentación completa y verificación lista para campo.',
    ),
    problem: l(
      'Equipment packages are integration projects, not single-process builds. A skid or custom equipment package combines structural fabrication, mechanical components (pumps, valves, drives), piping, instrumentation, electrical/control panels, and often a HMI/SCADA layer. Each subsystem is built by a different specialist; the failure mode is interface incompatibility discovered at integration, not at the individual subsystem level. Documentation requirements are heavy — P&ID, general arrangement drawings, electrical schematics, instrument lists, I/O lists, test records, material certificates, and operating manuals — and the package must arrive at the field with all of this complete and consistent, ready for installation and commissioning without rework.',
      'Los paquetes de equipos son proyectos de integración, no construcciones de proceso único. Un skid o paquete de equipo a medida combina fabricación estructural, componentes mecánicos (bombas, válvulas, accionamientos), tubería, instrumentación, tableros eléctrico/de control y a menudo una capa HMI/SCADA. Cada subsistema lo construye un especialista diferente; el modo de falla es incompatibilidad de interfaz descubierta en la integración, no a nivel del subsistema individual. Los requisitos de documentación son pesados — P&ID, planos de arreglo general, esquemas eléctricos, listas de instrumentos, listas de I/O, registros de prueba, certificados de material y manuales de operación — y el paquete debe llegar al campo con todo completo y consistente, listo para instalación y puesta en marcha sin retrabajo.',
    ),
    approach: l(
      'We manage equipment packages as integration programs. We begin with P&ID and general arrangement review against the operational requirements, then identify interface risks between structural, mechanical, piping, instrumentation, and electrical subsystems before build. Each subsystem is qualified through its own build and test cycle; integration is staged — mechanical completion, electrical completion, functional test, FAT (factory acceptance test), SAT (site acceptance test if applicable). The documentation package is built as the equipment is built, not generated at the end — P&ID, GA, electrical schematics, instrument lists, I/O lists, test records, material certificates, and operating manuals are released in a controlled package at delivery. Pre-shipment inspection covers dimensional, functional, and documentation completeness.',
      'Gestionamos los paquetes de equipos como programas de integración. Comenzamos con la revisión del P&ID y del arreglo general contra los requisitos operacionales, luego identificamos riesgos de interfaz entre los subsistemas estructural, mecánico, tubería, instrumentación y eléctrico antes de la construcción. Cada subsistema se califica a través de su propio ciclo de construcción y prueba; la integración se escalona — completitud mecánica, completitud eléctrica, prueba funcional, FAT (prueba de aceptación en fábrica), SAT (prueba de aceptación en sitio si aplica). El paquete de documentación se construye a medida que se construye el equipo, no se genera al final — P&ID, GA, esquemas eléctricos, listas de instrumentos, listas de I/O, registros de prueba, certificados de material y manuales de operación se liberan en un paquete controlado en la entrega. La inspección previa al envío cubre completitud dimensional, funcional y documental.',
    ),
    capabilities: a(
      [
        'Process skids (filtration, dosing, pumping, heat exchange)',
        'Structural frames and baseplates',
        'Mechanical assembly (pumps, valves, drives, gearboxes)',
        'Piping fabrication and installation (ASME B31.3 where applicable)',
        'Instrumentation mounting and tubing',
        'Control panel build (UL / CE as required)',
        'HMI/SCADA integration support',
        'FAT, SAT, and commissioning documentation',
      ],
      [
        'Skids de proceso (filtración, dosificación, bombeo, intercambio de calor)',
        'Bastidores estructurales y placas base',
        'Ensamblaje mecánico (bombas, válvulas, accionamientos, reductores)',
        'Fabricación e instalación de tubería (ASME B31.3 cuando aplica)',
        'Montaje de instrumentación y tubería de instrumento',
        'Construcción de tablero de control (UL / CE según se requiera)',
        'Soporte de integración HMI/SCADA',
        'Documentación FAT, SAT y puesta en marcha',
      ],
    ),
    relatedIndustries: ['industrial-equipment', 'food', 'mining', 'construction'],
    relatedServices: ['engineering', 'project-management', 'manufacturing-supervision'],
  },
  {
    id: 'renewable-energy',
    slug: l('renewable-energy', 'energia-renovable'),
    title: l('Renewable Energy', 'Energía Renovable'),
    summary: l(
      'Manufacturing and execution support for renewable energy infrastructure — solar mounting structures, electrical enclosures, and balance-of-plant assemblies with traceable materials.',
      'Soporte de manufactura y ejecución para infraestructura de energía renovable — estructuras de montaje solar, gabinetes eléctricos y conjuntos auxiliares de planta con materiales trazables.',
    ),
    problem: l(
      'Renewable energy projects combine large volumes, distributed sites, long service life, and demanding environmental conditions. Components must be durable (25+ year service life for solar), traceable (material certificates for structural members), and supplied in coordinated sequences against project schedules that span multiple sites and seasons. Long-lead items — structural steel, fasteners, electrical components — require early commitment and supplier qualification before the rest of the project can flow. Galvanic compatibility between aluminum structures, steel fasteners, and copper grounding is a quality input that must be designed in, not discovered in the field. Documentation — material certificates, traceability records, environmental certifications — must accompany the components to site, not arrive later.',
      'Los proyectos de energía renovable combinan grandes volúmenes, sitios distribuidos, larga vida de servicio y condiciones ambientales exigentes. Los componentes deben ser durables (25+ años de vida de servicio para solar), trazables (certificados de material para miembros estructurales) y suministrados en secuencias coordinadas contra cronogramas de proyecto que abarcan múltiples sitios y temporadas. Los artículos de largo plazo — acero estructural, herrajes, componentes eléctricos — requieren compromiso temprano y calificación de proveedores antes de que el resto del proyecto pueda fluir. La compatibilidad galvánica entre estructuras de aluminio, herrajes de acero y tierra de cobre es una entrada de calidad que debe diseñarse, no descubrirse en campo. La documentación — certificados de material, registros de trazabilidad, certificaciones ambientales — debe acompañar a los componentes al sitio, no llegar después.',
    ),
    approach: l(
      'We align engineering review, qualified supply, inspection, and logistics with project schedules. Material selection is verified against the operating environment — UV resistance, corrosion category (C1–C5 per ISO 9223), wind/snow loads, seismic category. Structural calculations are reviewed against local codes. Supplier qualification covers process capability (structural welding to AWS D1.1 or equivalent, hot-dip galvanizing to ASTM A123 / ISO 1461, anodizing to ASTM A879 / MIL-A-8625). Inspection covers dimensional verification, weld inspection (visual, dye penetrant, magnetic particle as required), coating thickness verification, and material certificate review. Logistics sequencing aligns supplier production with site installation windows — partial shipments, staged inventory near site, and documented chain of custody for traceability.',
      'Alineamos la revisión de ingeniería, el suministro calificado, la inspección y la logística con los cronogramas del proyecto. La selección de material se verifica contra el entorno operativo — resistencia UV, categoría de corrosión (C1–C5 según ISO 9223), cargas de viento/nieve, categoría sísmica. Los cálculos estructurales se revisan contra códigos locales. La calificación de proveedores cubre capacidad de proceso (soldadura estructural según AWS D1.1 o equivalente, galvanizado en caliente según ASTM A123 / ISO 1461, anodizado según ASTM A879 / MIL-A-8625). La inspección cubre verificación dimensional, inspección de soldadura (visual, tintas penetrantes, partículas magnéticas según se requiera), verificación de espesor de recubrimiento y revisión de certificados de material. La secuencia logística alinea la producción del proveedor con las ventanas de instalación en sitio — envíos parciales, inventario escalonado cerca del sitio y cadena de custodia documentada para trazabilidad.',
    ),
    capabilities: a(
      [
        'Solar mounting structures (fixed-tilt, single-axis tracker)',
        'Electrical enclosures (DC combiner, AC combiner, inverter skids)',
        'Structural steel fabrication (galvanized, painted)',
        'Aluminum extrusion components (mill, anodized, painted)',
        'Balance-of-plant assemblies',
        'Material traceability per EN 10204 3.1 / 3.2',
        'Welding qualification (AWS D1.1 / ISO 15614)',
        'Coating verification (thickness, adhesion)',
      ],
      [
        'Estructuras de montaje solar (inclinación fija, seguidor de eje único)',
        'Gabinetes eléctricos (combinador CC, combinador CA, skids de inversor)',
        'Fabricación de acero estructural (galvanizado, pintado)',
        'Componentes de extrusión de aluminio (crudo, anodizado, pintado)',
        'Conjuntos auxiliares de planta',
        'Trazabilidad de material según EN 10204 3.1 / 3.2',
        'Calificación de soldadura (AWS D1.1 / ISO 15614)',
        'Verificación de recubrimiento (espesor, adherencia)',
      ],
    ),
    relatedIndustries: ['energy', 'construction'],
    relatedServices: ['supplier-qualification', 'quality-control', 'supply-chain-development'],
  },
  {
    id: 'water-treatment',
    slug: l('water-treatment', 'tratamiento-de-agua'),
    title: l('Water & Wastewater Treatment', 'Tratamiento de Agua y Aguas Residuales'),
    summary: l(
      'Process equipment and fabricated packages for water and wastewater treatment systems — skids, vessels, piping, and integrated packages delivered with field-ready documentation.',
      'Equipos de proceso y paquetes fabricados para sistemas de tratamiento de agua y aguas residuales — skids, vasos, tubería y paquetes integrados entregados con documentación lista para campo.',
    ),
    problem: l(
      'Water and wastewater treatment equipment operates with corrosive fluids, variable pressures and temperatures, and stringent hygiene and environmental requirements. Material compatibility is a primary design driver — stainless steel (304L, 316L, duplex), FRP, and engineered plastics each have their place, and the wrong material selection causes failure within months, not years. Piping must meet pressure ratings and pass hydrostatic testing; vessels must meet code (ASME Section VIII or local equivalent). Pumps and instrumentation must be selected for the service — chemical compatibility, NPSH, flow range, accuracy. Integration is complex: a treatment skid combines frame, vessels, piping, pumps, valves, instrumentation, control panel, and HMI in a footprint that must ship, lift, and install without rework.',
      'Los equipos de tratamiento de agua y aguas residuales operan con fluidos corrosivos, presiones y temperaturas variables y requisitos estrictos de higiene y ambientales. La compatibilidad de material es un impulsor primario de diseño — acero inoxidable (304L, 316L, dúplex), FRP y plásticos de ingeniería cada uno tienen su lugar, y la selección incorrecta de material causa falla en meses, no años. La tubería debe cumplir calificaciones de presión y pasar prueba hidrostática; los vasos deben cumplir código (ASME Sección VIII o equivalente local). Las bombas e instrumentación deben seleccionarse para el servicio — compatibilidad química, NPSH, rango de flujo, precisión. La integración es compleja: un skid de tratamiento combina bastidor, vasos, tubería, bombas, válvulas, instrumentación, tablero de control y HMI en una huella que debe enviarse, izarse e instalarse sin retrabajo.',
    ),
    approach: l(
      'We coordinate process requirements with equipment fabrication and verification. P&ID is reviewed against the operating envelope — flow rates, pressures, temperatures, fluid composition. Material selection is verified for fluid compatibility (corrosion allowance, pitting resistance, crevice corrosion). Piping is fabricated and hydrostatically tested per ASME B31.3 or equivalent; vessels are fabricated to ASME Section VIII where applicable. Skid integration follows the equipment build approach — structural, mechanical, piping, instrumentation, electrical — with interface control between subsystems. Functional testing (FAT) covers pump performance, valve operation, instrumentation calibration, and control system function before shipment. Documentation — P&ID, GA, electrical schematics, instrument lists, material certificates, hydrotest records, calibration records, operating manuals — accompanies the equipment.',
      'Coordinamos los requisitos de proceso con la fabricación y verificación de equipos. El P&ID se revisa contra la envolvente operativa — caudales, presiones, temperaturas, composición del fluido. La selección de material se verifica para compatibilidad de fluido (margen de corrosión, resistencia a picadura, corrosión de hendidura). La tubería se fabrica y prueba hidrostáticamente según ASME B31.3 o equivalente; los vasos se fabrican según ASME Sección VIII cuando aplica. La integración del skid sigue el enfoque de construcción de equipos — estructural, mecánico, tubería, instrumentación, eléctrico — con control de interfaz entre subsistemas. Las pruebas funcionales (FAT) cubren desempeño de bomba, operación de válvulas, calibración de instrumentación y función del sistema de control antes del envío. La documentación — P&ID, GA, esquemas eléctricos, listas de instrumentos, certificados de material, registros de hidroprueba, registros de calibración, manuales de operación — acompaña al equipo.',
    ),
    capabilities: a(
      [
        'Filtration skids (media, cartridge, membrane)',
        'Dosing skids (chemical feed, polymer preparation)',
        'Vessels and tanks (ASME Section VIII where required)',
        'Piping fabrication (ASME B31.3, hydrostatic tested)',
        'Pump and valve integration',
        'Control panel and instrumentation integration',
        'HMI/SCADA integration support',
        'FAT including hydrotest, functional test, calibration',
      ],
      [
        'Skids de filtración (medio, cartucho, membrana)',
        'Skids de dosificación (alimentación química, preparación de polímero)',
        'Vasos y tanques (ASME Sección VIII cuando se requiera)',
        'Fabricación de tubería (ASME B31.3, prueba hidrostática)',
        'Integración de bombas y válvulas',
        'Integración de tablero de control e instrumentación',
        'Soporte de integración HMI/SCADA',
        'FAT incluyendo hidroprueba, prueba funcional, calibración',
      ],
    ),
    relatedIndustries: ['energy', 'mining', 'food', 'construction'],
    relatedServices: ['engineering', 'project-management', 'quality-control'],
  },
  {
    id: 'automation',
    slug: l('automation', 'automatizacion'),
    title: l('Industrial Automation', 'Automatización Industrial'),
    summary: l(
      'Automation modules, workstations, and integration support for repeatable industrial operations — with clearly defined interfaces between mechanics, controls, safety, and operators.',
      'Módulos de automatización, estaciones de trabajo y soporte de integración para operaciones industriales repetibles — con interfaces claramente definidas entre mecánica, controles, seguridad y operadores.',
    ),
    problem: l(
      'Automation projects live or die at interfaces. The mechanical engineer designs a fixture; the controls engineer specifies a sensor; the safety engineer designs a guard; the operator uses the result. When those disciplines work in isolation, the integrated system shows mechanical-positions-not-matching-sensor-targets, controls-not-aligned-with-operator-workflow, and safety-functions-not-integrated-with-the-machine-sequence. The cost of these mismatches is paid at commissioning — late nights, schedule slips, and engineering change orders that erode the project\'s commercial case. A second failure mode is scope ambiguity: what is included, what is the buyer\'s responsibility, what is the integrator\'s, what happens when a third-party component does not perform as expected.',
      'Los proyectos de automatización viven o mueren en las interfaces. El ingeniero mecánico diseña un dispositivo; el ingeniero de controles especifica un sensor; el ingeniero de seguridad diseña una guardia; el operador usa el resultado. Cuando esas disciplinas trabajan aisladas, el sistema integrado muestra posiciones mecánicas que no coinciden con objetivos de sensor, controles no alineados con el flujo de trabajo del operador y funciones de seguridad no integradas con la secuencia de la máquina. El costo de estos desajustes se paga en la puesta en marcha — noches largas, deslizamientos de cronograma y órdenes de cambio de ingeniería que erosionan el caso comercial del proyecto. Un segundo modo de falla es la ambigüedad de alcance: qué se incluye, qué es responsabilidad del comprador, qué es del integrador, qué pasa cuando un componente de terceros no funciona como se esperaba.',
    ),
    approach: l(
      'We define scope boundaries first — what is included, what is the buyer\'s responsibility, what is ours, what happens when third-party components underperform. Then we coordinate build partners across mechanical, controls, safety, and HMI disciplines. Interface definitions are documented before build starts: mechanical-to-sensor positions, sensor-to-control signals, control-to-safety interlocks, control-to-operator HMI behavior. Functional specification defines the agreed behavior at each operating mode (manual, auto, maintenance, fault). Build and test are staged — mechanical completion, electrical completion, functional test, FAT — with documentation built in parallel, not generated at the end. Commissioning support covers installation, SAT, and operator training where required.',
      'Definimos los límites de alcance primero — qué se incluye, qué es responsabilidad del comprador, qué es nuestra, qué pasa cuando componentes de terceros tienen bajo desempeño. Luego coordinamos socios de construcción entre disciplinas mecánica, controles, seguridad y HMI. Las definiciones de interfaz se documentan antes de iniciar la construcción: posiciones mecánicas-a-sensor, señales sensor-a-control, enclavamientos control-a-seguridad, comportamiento control-a-operador HMI. La especificación funcional define el comportamiento acordado en cada modo de operación (manual, auto, mantenimiento, falla). La construcción y prueba se escalonan — completitud mecánica, completitud eléctrica, prueba funcional, FAT — con documentación construida en paralelo, no generada al final. El soporte de puesta en marcha cubre instalación, SAT y capacitación de operadores cuando se requiera.',
    ),
    capabilities: a(
      [
        'Fixtures, nests, and workstations',
        'Conveying and handling modules',
        'Robot integration (pick-and-place, cobots)',
        'Control enclosures (UL 508A / CE)',
        'Sensor and actuator integration',
        'Safety interlock and category-3/4 systems',
        'HMI design and integration',
        'Functional specification and FAT documentation',
      ],
      [
        'Dispositivos, nidos y estaciones de trabajo',
        'Módulos de transporte y manejo',
        'Integración de robots (pick-and-place, cobots)',
        'Gabinetes de control (UL 508A / CE)',
        'Integración de sensores y actuadores',
        'Sistemas de enclavamiento de seguridad categoría 3/4',
        'Diseño e integración HMI',
        'Especificación funcional y documentación FAT',
      ],
    ),
    relatedIndustries: ['automotive', 'industrial-equipment', 'food', 'packaging', 'electronics'],
    relatedServices: ['engineering', 'project-management', 'manufacturing-supervision'],
  },
  {
    id: 'packaging',
    slug: l('packaging', 'empaque'),
    title: l('Packaging Solutions', 'Soluciones de Empaque'),
    summary: l(
      'Packaging components, machine change parts, and line integration support for product protection and line performance — designed around the production line, not just the product.',
      'Componentes de empaque, piezas de cambio de máquina y soporte de integración de línea para protección del producto y rendimiento de línea — diseñados alrededor de la línea de producción, no solo del producto.',
    ),
    problem: l(
      'Packaging must protect the product, fit the process, and remain reliable at production speed. A packaging component that looks right but does not run at line rate, jams in the capper, misregisters in the labeler, or fails the drop test causes more loss than any unit-price advantage can recover. Multi-component packaging — bottle, cap, label, shrink band, secondary carton — must be designed as a system; tolerance stack-up between components determines whether the line runs at 95% efficiency or 70%. Change parts for existing machinery must match the original equipment manufacturer\'s geometry, surface finish, and material specifications; substitutions cause downtime that the production schedule cannot absorb.',
      'El empaque debe proteger el producto, ajustarse al proceso y mantenerse confiable a velocidad de producción. Un componente de empaque que luce correcto pero no corre a velocidad de línea, se atasca en el tapón, se desalinea en el etiquetador o falla la prueba de caída causa más pérdida que cualquier ventaja de precio unitario pueda recuperar. El empaque multicomponente — botella, tapa, etiqueta, banda retráctil, cartón secundario — debe diseñarse como sistema; el apilamiento de tolerancias entre componentes determina si la línea corre a 95% de eficiencia o 70%. Las piezas de cambio para maquinaria existente deben coincidir con la geometría, acabado superficial y especificaciones de material del fabricante original del equipo; las sustituciones causan tiempo muerto que el cronograma de producción no puede absorber.',
    ),
    approach: l(
      'We connect product requirements with material selection, tooling, machine interfaces, and incoming inspection. Material selection (PET, HDPE, PP, PCR content) is matched to product compatibility, barrier requirements, and recyclability targets. Tooling is specified and qualified to deliver dimensional stability at production rate. Machine change parts are reverse-engineered or built to OEM specifications. Line integration support covers changeover procedures, incoming inspection criteria, and performance trending during the initial production period. Validation includes dimensional verification, drop testing, leak testing, and shelf-life testing where applicable.',
      'Conectamos los requisitos del producto con la selección de materiales, herramentales, interfaces de máquina e inspección de entrada. La selección de material (PET, HDPE, PP, contenido PCR) se ajusta a la compatibilidad con el producto, requisitos de barrera y objetivos de reciclabilidad. Los herramentales se especifican y califican para entregar estabilidad dimensional a velocidad de producción. Las piezas de cambio de máquina se reconstruyen por ingeniería inversa o se construyen según especificaciones OEM. El soporte de integración de línea cubre procedimientos de cambio, criterios de inspección de entrada y tendencia de desempeño durante el período inicial de producción. La validación incluye verificación dimensional, prueba de caída, prueba de fuga y prueba de vida en estante cuando aplica.',
    ),
    capabilities: a(
      [
        'Rigid molded packaging (bottles, caps, closures)',
        'Flexible packaging components',
        'Machine change parts (OEM-spec)',
        'Labeling and decoration coordination',
        'Material selection (PET, HDPE, PP, PCR)',
        'Line integration support',
        'Drop, leak, and shelf-life testing coordination',
        'Changeover and incoming inspection criteria',
      ],
      [
        'Empaque rígido moldeado (botellas, tapas, cierres)',
        'Componentes de empaque flexible',
        'Piezas de cambio de máquina (especie OEM)',
        'Coordinación de etiquetado y decoración',
        'Selección de material (PET, HDPE, PP, PCR)',
        'Soporte de integración de línea',
        'Coordinación de pruebas de caída, fuga y vida en estante',
        'Criterios de cambio y de inspección de entrada',
      ],
    ),
    relatedIndustries: ['consumer-goods', 'food', 'packaging'],
    relatedServices: ['product-development', 'tooling', 'quality-control'],
  },
  {
    id: 'custom-manufacturing',
    slug: l('custom-manufacturing', 'manufactura-a-medida'),
    title: l('Custom Manufacturing Programs', 'Programas de Manufactura a Medida'),
    summary: l(
      'Cross-process manufacturing for products that do not fit a standard catalog — structured technical packages, qualified multi-process routes, and governed execution.',
      'Manufactura multiproceso para productos que no encajan en un catálogo estándar — paquetes técnicos estructurados, rutas multiproceso calificadas y ejecución gobernada.',
    ),
    problem: l(
      'Custom products do not fit a single process or a single supplier. They require a practical path from incomplete or fluid requirements to repeatable output, often across multiple manufacturing processes and multiple suppliers. The failure mode is unmanaged complexity: scope creeps, suppliers are added without integration, technical baseline drifts, and the program accumulates hidden cost in late engineering changes, expedited logistics, and quality escapes. Custom does not mean uncontrolled — it means the structure must be designed for the specific program, not borrowed from a standard template that does not fit.',
      'Los productos a medida no encajan en un solo proceso ni en un solo proveedor. Requieren una ruta práctica desde requisitos incompletos o fluidos hasta salida repetible, a menudo a través de múltiples procesos de manufactura y múltiples proveedores. El modo de falla es complejidad no gestionada: el alcance se desliza, se agregan proveedores sin integración, la línea base técnica deriva y el programa acumula costo oculto en cambios tardíos de ingeniería, logística expedita y fugas de calidad. A medida no significa incontrolado — significa que la estructura debe diseñarse para el programa específico, no tomarse prestada de una plantilla estándar que no encaja.',
    ),
    approach: l(
      'We structure the technical package, select qualified processes, and govern execution. The technical package — drawings, BOM, specifications, control plan — is built explicitly even when input requirements are fluid; partial packages are released with clear "to be confirmed" markers rather than left ambiguous. Process routes are selected from qualified suppliers based on the part\'s functional and commercial requirements; multi-process assemblies are managed through interface control between processes. Execution is governed through the program management methodology — milestone tracking, risk register, change control — adapted to the program\'s scale. The result is a custom program that delivers consistent output without the chaos typically associated with custom work.',
      'Estructuramos el paquete técnico, seleccionamos procesos calificados y gobernamos la ejecución. El paquete técnico — planos, BOM, especificaciones, plan de control — se construye explícitamente incluso cuando los requisitos de entrada son fluidos; los paquetes parciales se liberan con marcadores claros de "por confirmar" en lugar de dejarlos ambiguos. Las rutas de proceso se seleccionan de proveedores calificados basados en los requisitos funcionales y comerciales de la pieza; los conjuntos multiproceso se gestionan a través de control de interfaz entre procesos. La ejecución se gobierna a través de la metodología de gestión de programas — seguimiento de hitos, registro de riesgos, control de cambios — adaptada a la escala del programa. El resultado es un programa a medida que entrega salida consistente sin el caos típicamente asociado con el trabajo a medida.',
    ),
    capabilities: a(
      [
        'Multi-process assemblies (plastic + metal + electronic)',
        'Low-to-medium volume production',
        'Custom testing and packaging',
        'Technical package construction from fluid inputs',
        'Multi-supplier interface control',
        'Program governance adapted to scale',
        'Engineering change control',
        'Production ramp-up support',
      ],
      [
        'Conjuntos multiproceso (plástico + metal + electrónico)',
        'Producción de bajo a mediano volumen',
        'Pruebas y embalaje a medida',
        'Construcción de paquete técnico desde entradas fluidas',
        'Control de interfaz multiproveedor',
        'Gobernanza de programa adaptada a escala',
        'Control de cambios de ingeniería',
        'Soporte de ramp-up de producción',
      ],
    ),
    relatedIndustries: ['automotive', 'medical', 'consumer-goods', 'electronics'],
    relatedServices: ['product-development', 'reverse-engineering', 'oem', 'odm'],
  },
];
